/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Santa.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Santa.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Santa" position={[-64.356, -6.113, 15.973]} rotation={[-Math.PI, 0.452, -Math.PI]} scale={[4.051, 4.051, 4.135]}>
        <primitive object={nodes.spine} />
        <primitive object={nodes.neutral_bone} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_1" geometry={nodes['12165_Santa_Claus_v1_l2000_1'].geometry} material={materials['santas face']} skeleton={nodes['12165_Santa_Claus_v1_l2000_1'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_2" geometry={nodes['12165_Santa_Claus_v1_l2000_2'].geometry} material={materials['white rough']} skeleton={nodes['12165_Santa_Claus_v1_l2000_2'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_3" geometry={nodes['12165_Santa_Claus_v1_l2000_3'].geometry} material={materials['white rough']} skeleton={nodes['12165_Santa_Claus_v1_l2000_3'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_4" geometry={nodes['12165_Santa_Claus_v1_l2000_4'].geometry} material={materials.Body} skeleton={nodes['12165_Santa_Claus_v1_l2000_4'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_5" geometry={nodes['12165_Santa_Claus_v1_l2000_5'].geometry} material={materials['white rough']} skeleton={nodes['12165_Santa_Claus_v1_l2000_5'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_6" geometry={nodes['12165_Santa_Claus_v1_l2000_6'].geometry} material={materials.shoes} skeleton={nodes['12165_Santa_Claus_v1_l2000_6'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_7" geometry={nodes['12165_Santa_Claus_v1_l2000_7'].geometry} material={materials['white rough']} skeleton={nodes['12165_Santa_Claus_v1_l2000_7'].skeleton} />
        <skinnedMesh name="12165_Santa_Claus_v1_l2000_8" geometry={nodes['12165_Santa_Claus_v1_l2000_8'].geometry} material={materials['white rough']} skeleton={nodes['12165_Santa_Claus_v1_l2000_8'].skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/world/split/Santa.glb')
