/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/AlienCave.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/AlienCave.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Alien" geometry={nodes.Alien.geometry} material={materials['alien skin']} position={[2.466, -21.832, -36.361]} rotation={[1.586, 0.217, -2.394]} scale={0.182} />
      <mesh name="alien_2" geometry={nodes.alien_2.geometry} material={materials['alien skin']} position={[2.342, -22.032, -38.37]} rotation={[1.542, 0.128, -0.332]} scale={0.182} />
      <group name="flying_sacuer" position={[-0.601, -19.746, -30.463]} rotation={[1.521, 0.232, -1.661]} scale={3.506}>
        <mesh name="flying_sacuer_1" geometry={nodes.flying_sacuer_1.geometry} material={materials['saucer darkblue']} />
        <mesh name="flying_sacuer_2" geometry={nodes.flying_sacuer_2.geometry} material={materials['saucer lightblue']} />
        <mesh name="flying_sacuer_3" geometry={nodes.flying_sacuer_3.geometry} material={materials['glowing ice']} />
        <mesh name="flying_sacuer_4" geometry={nodes.flying_sacuer_4.geometry} material={materials['glowing ice']} />
      </group>
      <mesh name="1222_Iceberg006" geometry={nodes['1222_Iceberg006'].geometry} material={materials['glowing ice']} position={[29.855, -21.909, -29.725]} rotation={[Math.PI / 2, 0, 1.774]} scale={[0.019, 0.049, 0.061]} />
      <mesh name="1222_Iceberg007" geometry={nodes['1222_Iceberg007'].geometry} material={materials['glowing ice']} position={[24.437, -22.196, -23.753]} rotation={[Math.PI / 2, 0, 1.774]} scale={[0.059, 0.089, 0.061]} />
      <mesh name="1222_Iceberg008" geometry={nodes['1222_Iceberg008'].geometry} material={materials['glowing ice']} position={[13.695, -22.96, -36.756]} rotation={[Math.PI / 2, 0, 0.391]} scale={[0.059, 0.089, 0.061]} />
      <mesh name="1222_Iceberg009" geometry={nodes['1222_Iceberg009'].geometry} material={materials['glowing ice']} position={[11.632, -20.732, -25.897]} rotation={[2.054, 1.047, -1.148]} scale={[0.059, 0.089, 0.061]} />
      <mesh name="1222_Iceberg010" geometry={nodes['1222_Iceberg010'].geometry} material={materials['glowing ice']} position={[29.855, -21.868, -29.725]} rotation={[Math.PI / 2, 0, 1.774]} scale={[0.019, 0.049, 0.061]} />
      <mesh name="1222_Iceberg011" geometry={nodes['1222_Iceberg011'].geometry} material={materials['glowing ice']} position={[-6.624, -25.201, -42.002]} rotation={[Math.PI / 2, 0, 0.582]} scale={[0.071, 0.161, 0.061]} />
      <mesh name="1222_Iceberg012" geometry={nodes['1222_Iceberg012'].geometry} material={materials['glowing ice']} position={[16.885, -9.323, -28.606]} rotation={[-1.545, -0.094, -0.841]} scale={[0.019, 0.019, 0.061]} />
      <mesh name="1222_Iceberg013" geometry={nodes['1222_Iceberg013'].geometry} material={materials['glowing ice']} position={[21.057, -7.384, -39.631]} rotation={[-1.647, -0.023, -0.841]} scale={[0.019, 0.019, 0.061]} />
    </group>
  )
}

useGLTF.preload('/AlienCave.glb')
