/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Bridge.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bridge.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Bridge" position={[-9.837, -7.071, 106.29]} rotation={[0.759, -0.484, -2.845]} scale={[1.685, 0.049, 0.114]}>
        <mesh name="Cube202" geometry={nodes.Cube202.geometry} material={materials.Wood_Light} />
        <mesh name="Cube202_1" geometry={nodes.Cube202_1.geometry} material={materials.Wood} />
        <mesh name="Cube202_2" geometry={nodes.Cube202_2.geometry} material={materials.rope} />
        <mesh name="Cube202_3" geometry={nodes.Cube202_3.geometry} material={materials['shiny metal']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bridge.glb')
