/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Church.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Church.glb')
  return (
    <group {...props} dispose={null}>
      <group name="church" position={[-42.559, -4.48, 161.178]} rotation={[-3.077, 0.553, 3.107]}>
        <mesh name="Scene028" geometry={nodes.Scene028.geometry} material={materials.Wood} />
        <mesh name="Scene028_1" geometry={nodes.Scene028_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene028_2" geometry={nodes.Scene028_2.geometry} material={materials.Wood_Light} />
        <mesh name="Scene028_3" geometry={nodes.Scene028_3.geometry} material={materials.Plaster} />
        <mesh name="Scene028_4" geometry={nodes.Scene028_4.geometry} material={materials['light_wood_01.001']} />
        <mesh name="Scene028_5" geometry={nodes.Scene028_5.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene028_6" geometry={nodes.Scene028_6.geometry} material={materials['pine_trunk.001']} />
        <mesh name="Scene028_7" geometry={nodes.Scene028_7.geometry} material={materials['rock_dark.001']} />
        <mesh name="Scene028_8" geometry={nodes.Scene028_8.geometry} material={materials['window_01_nightlight.010']} />
      </group>
      <group name="fence_snowy_02" position={[-35.042, -3.668, 154.783]} rotation={[3.006, 0.646, -3.034]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02001" position={[-30.648, -3.914, 150.006]} rotation={[0.086, -0.687, 0.122]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02002" position={[-41.827, -3.547, 153.025]} rotation={[3.141, 0.517, 3.077]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02003" position={[-39.311, -3.532, 149.127]} rotation={[3.087, 0.597, -3.131]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02004" position={[-36.416, -3.514, 145.698]} rotation={[3.087, 0.597, -3.131]}>
        <mesh name="Scene001" geometry={nodes.Scene001.geometry} material={materials.DarkWood} />
        <mesh name="Scene001_1" geometry={nodes.Scene001_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene001_2" geometry={nodes.Scene001_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_03" position={[-32.993, -4.052, 152.197]} rotation={[3.017, 1.01, -2.968]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="fence_snowy_03001" position={[-34.532, -4.318, 143.508]} rotation={[2.997, 1.009, -3.08]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="snowman_01" position={[-25.601, -5.191, 149.56]} rotation={[2.981, 1.008, 3.14]}>
        <mesh name="Scene046" geometry={nodes.Scene046.geometry} material={materials['black matte']} />
        <mesh name="Scene046_1" geometry={nodes.Scene046_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene046_2" geometry={nodes.Scene046_2.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene046_3" geometry={nodes.Scene046_3.geometry} material={materials['pine_trunk.001']} />
        <mesh name="Scene046_4" geometry={nodes.Scene046_4.geometry} material={materials['rock_dark.001']} />
      </group>
      <group name="streetlamp_01" position={[-33.518, -4.339, 157.107]} rotation={[2.94, 1.004, -2.945]}>
        <mesh name="Scene049" geometry={nodes.Scene049.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene049_1" geometry={nodes.Scene049_1.geometry} material={materials['rock_dark.001']} />
        <mesh name="Scene049_2" geometry={nodes.Scene049_2.geometry} material={materials['window_01_nightlight.010']} />
      </group>
      <group name="streetlamp_02" position={[-43.047, -4.097, 151.145]} rotation={[3.14, 1.014, 3.078]}>
        <mesh name="Scene044" geometry={nodes.Scene044.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene044_1" geometry={nodes.Scene044_1.geometry} material={materials['rock_dark.001']} />
        <mesh name="Scene044_2" geometry={nodes.Scene044_2.geometry} material={materials['window_01_nightlight.010']} />
      </group>
      <mesh name="rock_group_01" geometry={nodes.rock_group_01.geometry} material={materials['rock_dark.001']} position={[-37.185, -5.965, 170.388]} rotation={[-2.87, 0.997, 3.068]} />
      <mesh name="rock_group_02" geometry={nodes.rock_group_02.geometry} material={materials['rock_dark.001']} position={[-36.961, -5.385, 132.658]} rotation={[3.136, 1.014, -3.1]} />
      <mesh name="rock_group_02001" geometry={nodes.rock_group_02001.geometry} material={materials['rock_dark.001']} position={[-31.95, -5.362, 165.508]} rotation={[-2.857, 0.995, 3.052]} />
      <mesh name="rock_group_03" geometry={nodes.rock_group_03.geometry} material={materials['rock_dark.001']} position={[-55.206, -5.384, 158.391]} rotation={[2.868, 0.996, -2.87]} />
      <mesh name="rock_group_03001" geometry={nodes.rock_group_03001.geometry} material={materials['rock_dark.001']} position={[-32.79, -5.967, 171.36]} rotation={[-2.857, 0.995, 3.052]} />
      <mesh name="rock_group_04" geometry={nodes.rock_group_04.geometry} material={materials['rock_dark.001']} position={[-19.694, -5.37, 146.998]} rotation={[3.091, 1.013, 3.095]} />
      <mesh name="snow_pile_01" geometry={nodes.snow_pile_01.geometry} material={materials['ground_snow.001']} position={[-44.52, -4.967, 144.04]} rotation={[-3.115, 1.013, 3.113]} />
    </group>
  )
}

useGLTF.preload('/Church.glb')
