/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Collectibles.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Collectibles.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="collectible_1" geometry={nodes.collectible_1.geometry} material={materials['Material.003']} position={[92.778, -17.887, -36.945]} rotation={[-Math.PI, 1.308, -Math.PI]} />
      <mesh name="collectible_1001" geometry={nodes.collectible_1001.geometry} material={materials['Material.003']} position={[92.806, -17.887, 32.917]} rotation={[-Math.PI, 1.308, -Math.PI]} />
      <mesh name="collectible_1002" geometry={nodes.collectible_1002.geometry} material={materials['Material.003']} position={[104.392, -17.887, 55.354]} rotation={[-Math.PI, 1.308, -Math.PI]} />
      <mesh name="collectible_1003" geometry={nodes.collectible_1003.geometry} material={materials['Material.003']} position={[44.054, -18.49, -57.612]} rotation={[-Math.PI, 1.308, -Math.PI]} />
      <mesh name="collectible_1004" geometry={nodes.collectible_1004.geometry} material={materials['Material.003']} position={[58.333, -3.275, 104.935]} rotation={[-Math.PI, 1.308, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Collectibles.glb')
