/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Floor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Floor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="ground_church" geometry={nodes.ground_church.geometry} material={materials['ground_snow.001']} position={[-38.352, -5.946, 138.887]} rotation={[-Math.PI, 1.014, -Math.PI]} />
      <mesh name="ground_santa" geometry={nodes.ground_santa.geometry} material={materials['ground_snow.001']} position={[12.987, -7.142, 65.029]} rotation={[-Math.PI, 1.308, -Math.PI]} />
      <mesh name="ground_start" geometry={nodes.ground_start.geometry} material={materials['ground_snow.001']} position={[0.082, -15.089, 17.15]} rotation={[-Math.PI, 1.308, -Math.PI]} />
      <mesh name="ground_village" geometry={nodes.ground_village.geometry} material={materials['ground_snow.001']} position={[76.515, -11.106, 117.637]} rotation={[3.12, 1.302, -3.094]} />
      <mesh name="ground_lower" geometry={nodes.ground_lower.geometry} material={materials['ground_snow.001']} position={[71.773, -25.618, -3.347]} rotation={[0, -0.214, 0]} scale={[2.393, 1, 2.689]} />
      <mesh name="ground_village_2" geometry={nodes.ground_village_2.geometry} material={materials['ground_snow.001']} position={[53.235, -12.611, 111.92]} rotation={[0, 0.055, 0]} />
      <group name="road_1" position={[60.807, -9.376, 76.451]} rotation={[-1.015, 1.506, 0.835]}>
        <mesh name="Scene042" geometry={nodes.Scene042.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene042_1" geometry={nodes.Scene042_1.geometry} material={materials['road_asphalt.001']} />
      </group>
      <group name="road_4" position={[57.857, -18.316, 24.391]} rotation={[0.169, -1.399, 0.344]}>
        <mesh name="Scene042" geometry={nodes.Scene042.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene042_1" geometry={nodes.Scene042_1.geometry} material={materials['road_asphalt.001']} />
      </group>
      <group name="road_2" position={[58.772, -12.51, 59.916]} rotation={[-0.538, -1.517, -0.383]}>
        <mesh name="Scene008" geometry={nodes.Scene008.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene008_1" geometry={nodes.Scene008_1.geometry} material={materials['road_asphalt.001']} />
      </group>
      <group name="road_3" position={[60.558, -15.517, 42.158]} rotation={[1.499, 1.413, -1.638]}>
        <mesh name="Scene009" geometry={nodes.Scene009.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene009_1" geometry={nodes.Scene009_1.geometry} material={materials['road_asphalt.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Floor.glb')
