/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/LowerLevel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LowerLevel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="1222_Iceberg" geometry={nodes['1222_Iceberg'].geometry} material={materials.ice} position={[117.044, -47.496, -72.755]} rotation={[Math.PI / 2, 0, -1.833]} scale={0.718} />
      <mesh name="1222_Iceberg001" geometry={nodes['1222_Iceberg001'].geometry} material={materials.ice} position={[126.36, -21.454, -33.329]} rotation={[Math.PI / 2, 0, -1.833]} scale={0.061} />
      <mesh name="1222_Iceberg002" geometry={nodes['1222_Iceberg002'].geometry} material={materials.ice} position={[125.526, -21.736, -26.457]} rotation={[Math.PI / 2, 0, 1.742]} scale={[0.177, 0.097, 0.129]} />
      <mesh name="1222_Iceberg003" geometry={nodes['1222_Iceberg003'].geometry} material={materials.ice} position={[117.353, -21.414, -13.856]} rotation={[Math.PI / 2, 0, 1.742]} scale={[0.178, 0.098, 0.13]} />
      <mesh name="1222_Iceberg004" geometry={nodes['1222_Iceberg004'].geometry} material={materials.ice} position={[76.57, -23.776, -59.402]} rotation={[Math.PI / 2, 0, -1.833]} scale={0.125} />
      <mesh name="1222_Iceberg005" geometry={nodes['1222_Iceberg005'].geometry} material={materials.ice} position={[63.744, -23.498, -35.023]} rotation={[Math.PI / 2, 0, -0.292]} scale={[0.114, 0.204, 0.154]} />
      <group name="pine_medium_snowy_01002" position={[83.272, -19.3, 58.48]} rotation={[0.461, -0.192, -0.073]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01009" position={[92.34, -19.752, 62.382]} rotation={[0.47, -0.192, -0.083]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01010" position={[104.23, -18.869, 48.017]} rotation={[0.053, -0.214, -0.136]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01011" position={[98.402, -19.215, 53.573]} rotation={[0.461, -0.192, -0.073]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01012" position={[88.151, -18.457, 45.729]} rotation={[0.053, -0.214, -0.136]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01013" position={[104.508, -18.676, 37.501]} rotation={[0.322, -0.159, 0.01]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01014" position={[112.131, -18.694, 45.41]} rotation={[0.252, -0.208, 0.103]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01015" position={[80.221, -18.202, 41.77]} rotation={[0.136, -0.212, -0.185]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01016" position={[113.598, -18.259, 34.281]} rotation={[-0.112, -0.213, 0.095]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01017" position={[117.4, -18.457, 40.703]} rotation={[0.252, -0.208, 0.103]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01018" position={[85.922, -18.307, 38.468]} rotation={[0.136, -0.212, -0.185]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01019" position={[98.091, -18.59, 37.383]} rotation={[0.053, -0.214, -0.136]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01020" position={[120.295, -19.385, 33.704]} rotation={[2.991, -1.026, 3.106]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01006" position={[129.014, -20.439, 6.404]} rotation={[2.84, 1.506, -2.903]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01007" position={[100.792, -19.782, 60.41]} rotation={[0.47, -0.192, -0.083]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01008" position={[93.058, -19.131, 53.62]} rotation={[0.461, -0.192, -0.073]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01009" position={[111.247, -18.984, 55.187]} rotation={[0.205, -0.21, 0.094]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01010" position={[83.817, -18.748, 50.62]} rotation={[0.461, -0.192, -0.073]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01011" position={[93.013, -19.26, 40.357]} rotation={[0.053, -0.214, -0.136]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01012" position={[88.234, -19.348, 57.797]} rotation={[0.461, -0.192, -0.073]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01005" position={[129.922, -20.75, 17.924]} rotation={[-2.124, 1.453, 2.134]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01004" position={[95.988, -18.652, 46.04]} rotation={[0.053, -0.214, -0.136]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01005" position={[76.6, -18.64, 50.875]} rotation={[0.465, -0.192, -0.06]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01006" position={[81.923, -19.863, 66.457]} rotation={[0.461, -0.192, -0.073]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01007" position={[107.639, -19.195, 61.505]} rotation={[0.205, -0.21, 0.094]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01008" position={[119.396, -18.687, 48.826]} rotation={[0.252, -0.208, 0.103]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01009" position={[86.77, -20.152, 69.116]} rotation={[0.47, -0.192, -0.083]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01010" position={[98.061, -20.217, 66.979]} rotation={[0.47, -0.192, -0.083]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01011" position={[125.133, -20.687, 40.753]} rotation={[0.431, 1.192, -0.194]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="Tent_Cube001" position={[126.032, -18.403, 13.22]} rotation={[1.64, -0.13, 1.384]} scale={3.824}>
        <mesh name="Tent_Cube001_1" geometry={nodes.Tent_Cube001_1.geometry} material={materials.Tent_M} />
        <mesh name="Tent_Cube001_2" geometry={nodes.Tent_Cube001_2.geometry} material={materials.Tent_S} />
      </group>
      <mesh name="rock_small_01" geometry={nodes.rock_small_01.geometry} material={materials['rock_dark.001']} position={[104.53, -19.739, 24.182]} rotation={[-2.885, 1.507, 2.893]} scale={[1.057, 1, 1.917]} />
      <mesh name="rock_small_02" geometry={nodes.rock_small_02.geometry} material={materials['rock_dark.001']} position={[100.73, -19.8, 14.698]} rotation={[-3.027, 0.703, 3.117]} scale={[1.071, 0.63, 2.116]} />
      <group name="fence_snowy_03002" position={[125.162, -20.078, 5.651]} rotation={[2.465, 1.491, -2.558]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="fence_snowy_03003" position={[125.677, -20.188, 7.506]} rotation={[-2.609, 1.502, 2.125]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="log" position={[112.205, -18.784, 11.704]} rotation={[1.528, 0.086, -2.654]} scale={[2.815, 2.208, 1.988]}>
        <mesh name="group1305922676" geometry={nodes.group1305922676.geometry} material={materials['pine_trunk.001']} />
        <mesh name="group1305922676_1" geometry={nodes.group1305922676_1.geometry} material={materials['light_wood_01.001']} />
      </group>
      <group name="log_2" position={[112.229, -18.754, 23.618]} rotation={[1.595, -0.058, -0.889]} scale={[2.815, 2.208, 1.988]}>
        <mesh name="group1305922676001" geometry={nodes.group1305922676001.geometry} material={materials['pine_trunk.001']} />
        <mesh name="group1305922676001_1" geometry={nodes.group1305922676001_1.geometry} material={materials['light_wood_01.001']} />
      </group>
      <group name="firewoods_01" position={[115.838, -20.362, 3.828]} rotation={[3.086, 0.201, -3.123]} scale={3.024}>
        <mesh name="Scene043" geometry={nodes.Scene043.geometry} material={materials['light_wood_01.001']} />
        <mesh name="Scene043_1" geometry={nodes.Scene043_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene043_2" geometry={nodes.Scene043_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <mesh name="Boat-ver1" geometry={nodes['Boat-ver1'].geometry} material={materials['Texture-base.014']} position={[100.49, -18.236, -11.124]} rotation={[1.662, 0.21, -1.727]} scale={4.822} />
      <group name="Bonfire001" position={[106.779, -19.195, 18.524]} rotation={[-Math.PI, 1.308, -Math.PI]} scale={9.855}>
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.Wood} />
        <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials.WoodSide} />
        <mesh name="Cylinder004_2" geometry={nodes.Cylinder004_2.geometry} material={materials['rock_dark.001']} />
        <mesh name="Cylinder004_3" geometry={nodes.Cylinder004_3.geometry} material={materials.Wood} />
      </group>
      <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cube001_Cube004" geometry={nodes.Cube001_Cube004.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cube002_Cube005" geometry={nodes.Cube002_Cube005.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cube003_Cube006" geometry={nodes.Cube003_Cube006.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cube005_Cube008" geometry={nodes.Cube005_Cube008.geometry} material={materials['dark grey rough']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cube006_Cube001" geometry={nodes.Cube006_Cube001.geometry} material={materials['rough black']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <group name="Cube_Cube002" position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]}>
        <mesh name="Cube_Cube002_1" geometry={nodes.Cube_Cube002_1.geometry} material={materials['rough black']} />
        <mesh name="Cube_Cube002_2" geometry={nodes.Cube_Cube002_2.geometry} material={materials.Body} />
        <mesh name="Cube_Cube002_3" geometry={nodes.Cube_Cube002_3.geometry} material={materials.Yellow} />
        <mesh name="Cube_Cube002_4" geometry={nodes.Cube_Cube002_4.geometry} material={materials['car glass']} />
      </group>
      <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['rough black']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['rough black']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['rough black']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
      <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['rough black']} position={[124.807, -21.419, 25.998]} rotation={[1.611, -0.147, 1.338]} />
    </group>
  )
}

useGLTF.preload('/LowerLevel.glb')
