/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Start.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Start.glb')
  return (
    <group {...props} dispose={null}>
      <group name="pine_medium_snowy_01" position={[10.036, -7.579, 5.797]} rotation={[2.952, 1.304, -3.05]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01001" position={[-7.939, -7.954, 26.838]} rotation={[-3.079, 1.308, 3.089]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01003" position={[19.043, -8.441, 20.627]} rotation={[2.551, 1.258, -2.64]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01004" position={[-10.667, -8.057, 18.058]} rotation={[3.116, 1.308, 3.056]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01005" position={[-13.992, -8.664, 5.176]} rotation={[2.751, 1.288, -2.737]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01007" position={[20.296, -7.986, 12.395]} rotation={[2.613, 1.269, -2.657]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01008" position={[10.783, -7.376, 10.622]} rotation={[-2.751, 1.288, 2.841]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01" position={[11.725, -7.801, 16.889]} rotation={[-2.773, 1.29, 2.793]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01001" position={[-13.945, -8.297, 24.469]} rotation={[-3.033, 1.307, 3.105]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01002" position={[19.165, -8.101, 8.096]} rotation={[2.613, 1.269, -2.657]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01003" position={[-19.263, -8.127, 16.72]} rotation={[-2.996, 1.306, 3.005]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01004" position={[-17.653, -8.252, 10.394]} rotation={[-2.922, 1.302, 2.959]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01006" position={[15.057, -7.826, 4.663]} rotation={[2.534, 1.255, -2.635]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01" position={[-14.77, -7.655, 13.809]} rotation={[-2.815, 1.294, 2.876]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01001" position={[15.278, -8.652, -1.787]} rotation={[2.534, 1.255, -2.635]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01002" position={[-10.986, -7.991, 23.73]} rotation={[-2.762, 1.289, 2.806]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01003" position={[16.082, -7.307, 13.966]} rotation={[2.974, 1.305, -3.02]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Start.glb')
