/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/AlienCave.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/AlienCave.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Alien" geometry={nodes.Alien.geometry} material={materials['alien skin']} position={[33.164, -21.832, 16.755]} rotation={[1.357, -0.042, -0.564]} scale={0.182} />
      <mesh name="alien_2" geometry={nodes.alien_2.geometry} material={materials['alien skin']} position={[35.136, -22.032, 17.157]} rotation={[1.455, -0.06, 1.496]} scale={0.182} />
      <group name="flying_sacuer" position={[28.264, -19.746, 12.263]} rotation={[1.358, -0.106, 0.155]} scale={3.506}>
        <mesh name="flying_sacuer_1" geometry={nodes.flying_sacuer_1.geometry} material={materials['saucer darkblue']} />
        <mesh name="flying_sacuer_2" geometry={nodes.flying_sacuer_2.geometry} material={materials['saucer lightblue']} />
        <mesh name="flying_sacuer_3" geometry={nodes.flying_sacuer_3.geometry} material={materials['glowing ice']} />
        <mesh name="flying_sacuer_4" geometry={nodes.flying_sacuer_4.geometry} material={materials['glowing ice']} />
      </group>
      <mesh name="1222_Iceberg006" geometry={nodes['1222_Iceberg006'].geometry} material={materials['glowing ice']} position={[19.649, -21.909, 41.485]} rotation={[Math.PI / 2, 0, -2.676]} scale={[0.019, 0.049, 0.061]} />
      <mesh name="1222_Iceberg007" geometry={nodes['1222_Iceberg007'].geometry} material={materials['glowing ice']} position={[15.287, -22.196, 34.702]} rotation={[Math.PI / 2, 0, -2.676]} scale={[0.059, 0.089, 0.061]} />
      <mesh name="1222_Iceberg008" geometry={nodes['1222_Iceberg008'].geometry} material={materials['glowing ice']} position={[30.632, -22.96, 27.702]} rotation={[Math.PI / 2, 0, 2.225]} scale={[0.059, 0.089, 0.061]} />
      <mesh name="1222_Iceberg009" geometry={nodes['1222_Iceberg009'].geometry} material={materials['glowing ice']} position={[20.68, -20.732, 22.893]} rotation={[0.459, 0, 0.967]} scale={[0.059, 0.089, 0.061]} />
      <mesh name="1222_Iceberg010" geometry={nodes['1222_Iceberg010'].geometry} material={materials['glowing ice']} position={[19.649, -21.868, 41.485]} rotation={[Math.PI / 2, 0, -2.676]} scale={[0.019, 0.049, 0.061]} />
      <mesh name="1222_Iceberg011" geometry={nodes['1222_Iceberg011'].geometry} material={materials['glowing ice']} position={[40.97, -25.201, 9.44]} rotation={[Math.PI / 2, 0, 2.416]} scale={[0.071, 0.161, 0.061]} />
      <mesh name="1222_Iceberg012" geometry={nodes['1222_Iceberg012'].geometry} material={materials['glowing ice']} position={[21.934, -9.323, 28.668]} rotation={[-1.668, 0, -2.676]} scale={[0.019, 0.019, 0.061]} />
      <mesh name="1222_Iceberg013" geometry={nodes['1222_Iceberg013'].geometry} material={materials['glowing ice']} position={[31.499, -7.384, 35.558]} rotation={[-1.573, 0.08, -2.673]} scale={[0.019, 0.019, 0.061]} />
    </group>
  )
}

useGLTF.preload('/AlienCave.glb')
