/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/ChristmasStuff.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/ChristmasStuff.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Node001" position={[18.389, -5.417, 34.706]} rotation={[-0.205, 0.134, -0.246]} scale={8.225}>
        <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials['mat8.001']} />
        <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['mat9.001']} />
      </group>
      <group name="Node004" position={[-4.095, -5.541, 148.184]} rotation={[-0.205, 0.134, -0.246]} scale={8.225}>
        <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials['mat8.001']} />
        <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['mat9.001']} />
      </group>
      <group name="Node002" position={[11.253, -5.417, 32.912]} rotation={[0.159, -0.06, 0.185]} scale={8.225}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials['mat8.001']} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials['mat21.002']} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials['mat12.002']} />
      </group>
      <group name="Node005" position={[-44.378, -3.941, 121.168]} rotation={[0.159, -0.06, 0.185]} scale={8.225}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials['mat8.001']} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials['mat21.002']} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials['mat12.002']} />
      </group>
      <group name="Node003" position={[-8.505, -5.513, 36.553]} rotation={[1.821, 0.109, -0.333]} scale={4.881}>
        <mesh name="Node-Mesh003" geometry={nodes['Node-Mesh003'].geometry} material={materials['mat8.001']} />
        <mesh name="Node-Mesh003_1" geometry={nodes['Node-Mesh003_1'].geometry} material={materials['mat9.001']} />
      </group>
      <group name="Node006" position={[-21.931, -2.274, 155.327]} rotation={[0.015, 0.13, 0.129]} scale={4.881}>
        <mesh name="Node-Mesh003" geometry={nodes['Node-Mesh003'].geometry} material={materials['mat8.001']} />
        <mesh name="Node-Mesh003_1" geometry={nodes['Node-Mesh003_1'].geometry} material={materials['mat9.001']} />
      </group>
      <group name="Node007" position={[-29.032, -2.218, 114.454]} rotation={[0.35, -0.038, -0.338]} scale={4.881}>
        <mesh name="Node-Mesh004" geometry={nodes['Node-Mesh004'].geometry} material={materials['mat8.002']} />
        <mesh name="Node-Mesh004_1" geometry={nodes['Node-Mesh004_1'].geometry} material={materials['mat9.002']} />
      </group>
      <group name="Node008" position={[49.306, -17.303, 19.526]} rotation={[-2.93, -0.093, -2.942]} scale={7.836}>
        <mesh name="Node-Mesh005" geometry={nodes['Node-Mesh005'].geometry} material={materials['mat8.003']} />
        <mesh name="Node-Mesh005_1" geometry={nodes['Node-Mesh005_1'].geometry} material={materials['mat9.003']} />
      </group>
      <group name="Node009" position={[78.608, -17.444, 19.111]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.802}>
        <mesh name="Node-Mesh006" geometry={nodes['Node-Mesh006'].geometry} material={materials['mat8.003']} />
        <mesh name="Node-Mesh006_1" geometry={nodes['Node-Mesh006_1'].geometry} material={materials['mat21.004']} />
        <mesh name="Node-Mesh006_2" geometry={nodes['Node-Mesh006_2'].geometry} material={materials['mat12.004']} />
      </group>
      <group name="Node010" position={[75.819, -16.706, 24.392]} rotation={[-Math.PI, 0, -Math.PI]} scale={3.579}>
        <mesh name="Node-Mesh007" geometry={nodes['Node-Mesh007'].geometry} material={materials['mat8.003']} />
        <mesh name="Node-Mesh007_1" geometry={nodes['Node-Mesh007_1'].geometry} material={materials['mat9.003']} />
      </group>
      <group name="Node011" position={[75.825, -17.355, 25.928]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.475}>
        <mesh name="Node-Mesh008" geometry={nodes['Node-Mesh008'].geometry} material={materials['mat8.004']} />
        <mesh name="Node-Mesh008_1" geometry={nodes['Node-Mesh008_1'].geometry} material={materials['mat9.004']} />
      </group>
      <group name="Node012" position={[32.701, -18.453, -69.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={6.605}>
        <mesh name="Node-Mesh009" geometry={nodes['Node-Mesh009'].geometry} material={materials['mat8.005']} />
        <mesh name="Node-Mesh009_1" geometry={nodes['Node-Mesh009_1'].geometry} material={materials['mat9.005']} />
      </group>
      <group name="Node013" position={[29.931, -17.658, -52.9]} rotation={[0.159, -0.06, 0.185]} scale={8.225}>
        <mesh name="Node-Mesh010" geometry={nodes['Node-Mesh010'].geometry} material={materials['mat8.006']} />
        <mesh name="Node-Mesh010_1" geometry={nodes['Node-Mesh010_1'].geometry} material={materials['mat21.007']} />
        <mesh name="Node-Mesh010_2" geometry={nodes['Node-Mesh010_2'].geometry} material={materials['mat12.007']} />
      </group>
      <group name="group375406252" position={[-11.811, -2.514, 73.928]} scale={20.171}>
        <mesh name="mesh375406252" geometry={nodes.mesh375406252.geometry} material={materials['mat12.001']} />
        <mesh name="mesh375406252_1" geometry={nodes.mesh375406252_1.geometry} material={materials.mat8} />
        <mesh name="mesh375406252_2" geometry={nodes.mesh375406252_2.geometry} material={materials['mat21.001']} />
        <mesh name="mesh375406252_3" geometry={nodes.mesh375406252_3.geometry} material={materials.mat1} />
        <mesh name="mesh375406252_4" geometry={nodes.mesh375406252_4.geometry} material={materials.mat10} />
        <mesh name="mesh375406252_5" geometry={nodes.mesh375406252_5.geometry} material={materials.mat5} />
        <mesh name="mesh375406252_6" geometry={nodes.mesh375406252_6.geometry} material={materials['pine_green.001']} />
        <mesh name="mesh375406252_7" geometry={nodes.mesh375406252_7.geometry} material={materials.mat3} />
        <mesh name="mesh375406252_8" geometry={nodes.mesh375406252_8.geometry} material={materials.mat20} />
        <mesh name="mesh375406252_9" geometry={nodes.mesh375406252_9.geometry} material={materials.mat9} />
      </group>
      <group name="group375406252001" position={[-48.31, -0.767, 132.244]} scale={20.171}>
        <mesh name="mesh375406252" geometry={nodes.mesh375406252.geometry} material={materials['mat12.001']} />
        <mesh name="mesh375406252_1" geometry={nodes.mesh375406252_1.geometry} material={materials.mat8} />
        <mesh name="mesh375406252_2" geometry={nodes.mesh375406252_2.geometry} material={materials['mat21.001']} />
        <mesh name="mesh375406252_3" geometry={nodes.mesh375406252_3.geometry} material={materials.mat1} />
        <mesh name="mesh375406252_4" geometry={nodes.mesh375406252_4.geometry} material={materials.mat10} />
        <mesh name="mesh375406252_5" geometry={nodes.mesh375406252_5.geometry} material={materials.mat5} />
        <mesh name="mesh375406252_6" geometry={nodes.mesh375406252_6.geometry} material={materials['pine_green.001']} />
        <mesh name="mesh375406252_7" geometry={nodes.mesh375406252_7.geometry} material={materials.mat3} />
        <mesh name="mesh375406252_8" geometry={nodes.mesh375406252_8.geometry} material={materials.mat20} />
        <mesh name="mesh375406252_9" geometry={nodes.mesh375406252_9.geometry} material={materials.mat9} />
      </group>
      <group name="group375406252002" position={[63.444, -16.219, -61.648]} scale={20.171}>
        <mesh name="mesh375406252" geometry={nodes.mesh375406252.geometry} material={materials['mat12.001']} />
        <mesh name="mesh375406252_1" geometry={nodes.mesh375406252_1.geometry} material={materials.mat8} />
        <mesh name="mesh375406252_2" geometry={nodes.mesh375406252_2.geometry} material={materials['mat21.001']} />
        <mesh name="mesh375406252_3" geometry={nodes.mesh375406252_3.geometry} material={materials.mat1} />
        <mesh name="mesh375406252_4" geometry={nodes.mesh375406252_4.geometry} material={materials.mat10} />
        <mesh name="mesh375406252_5" geometry={nodes.mesh375406252_5.geometry} material={materials.mat5} />
        <mesh name="mesh375406252_6" geometry={nodes.mesh375406252_6.geometry} material={materials['pine_green.001']} />
        <mesh name="mesh375406252_7" geometry={nodes.mesh375406252_7.geometry} material={materials.mat3} />
        <mesh name="mesh375406252_8" geometry={nodes.mesh375406252_8.geometry} material={materials.mat20} />
        <mesh name="mesh375406252_9" geometry={nodes.mesh375406252_9.geometry} material={materials.mat9} />
      </group>
      <mesh name="group570321177" geometry={nodes.group570321177.geometry} material={materials['mat12.001']} position={[-11.811, -2.514, 73.928]} scale={20.171} />
      <mesh name="group570321177001" geometry={nodes.group570321177001.geometry} material={materials['mat12.001']} position={[-48.31, -0.767, 132.244]} scale={20.171} />
      <mesh name="group570321177002" geometry={nodes.group570321177002.geometry} material={materials['mat12.001']} position={[63.444, -16.219, -61.648]} scale={20.171} />
      <mesh name="group718220577" geometry={nodes.group718220577.geometry} material={materials['mat12.001']} position={[-11.811, -2.514, 73.928]} scale={20.171} />
      <mesh name="group718220577001" geometry={nodes.group718220577001.geometry} material={materials['mat12.001']} position={[-48.31, -0.767, 132.244]} scale={20.171} />
      <mesh name="group718220577002" geometry={nodes.group718220577002.geometry} material={materials['mat12.001']} position={[63.444, -16.219, -61.648]} scale={20.171} />
      <mesh name="group838493682" geometry={nodes.group838493682.geometry} material={materials['mat12.001']} position={[-11.811, -2.514, 73.928]} scale={20.171} />
      <mesh name="group838493682001" geometry={nodes.group838493682001.geometry} material={materials['mat12.001']} position={[-48.31, -0.767, 132.244]} scale={20.171} />
      <mesh name="group838493682002" geometry={nodes.group838493682002.geometry} material={materials['mat12.001']} position={[63.444, -16.219, -61.648]} scale={20.171} />
      <group name="group899378052" position={[-11.811, -2.514, 73.928]} scale={20.171}>
        <mesh name="mesh899378052" geometry={nodes.mesh899378052.geometry} material={materials.mat9} />
        <mesh name="mesh899378052_1" geometry={nodes.mesh899378052_1.geometry} material={materials.mat8} />
        <mesh name="mesh899378052_2" geometry={nodes.mesh899378052_2.geometry} material={materials['mat21.001']} />
        <mesh name="mesh899378052_3" geometry={nodes.mesh899378052_3.geometry} material={materials['mat12.001']} />
      </group>
      <group name="group899378052001" position={[-48.31, -0.767, 132.244]} scale={20.171}>
        <mesh name="mesh899378052" geometry={nodes.mesh899378052.geometry} material={materials.mat9} />
        <mesh name="mesh899378052_1" geometry={nodes.mesh899378052_1.geometry} material={materials.mat8} />
        <mesh name="mesh899378052_2" geometry={nodes.mesh899378052_2.geometry} material={materials['mat21.001']} />
        <mesh name="mesh899378052_3" geometry={nodes.mesh899378052_3.geometry} material={materials['mat12.001']} />
      </group>
      <group name="group899378052002" position={[63.444, -16.219, -61.648]} scale={20.171}>
        <mesh name="mesh899378052" geometry={nodes.mesh899378052.geometry} material={materials.mat9} />
        <mesh name="mesh899378052_1" geometry={nodes.mesh899378052_1.geometry} material={materials.mat8} />
        <mesh name="mesh899378052_2" geometry={nodes.mesh899378052_2.geometry} material={materials['mat21.001']} />
        <mesh name="mesh899378052_3" geometry={nodes.mesh899378052_3.geometry} material={materials['mat12.001']} />
      </group>
      <mesh name="group1174422657" geometry={nodes.group1174422657.geometry} material={materials['mat12.001']} position={[-11.811, -2.514, 73.928]} scale={20.171} />
      <mesh name="group1174422657001" geometry={nodes.group1174422657001.geometry} material={materials['mat12.001']} position={[-48.31, -0.767, 132.244]} scale={20.171} />
      <mesh name="group1174422657002" geometry={nodes.group1174422657002.geometry} material={materials['mat12.001']} position={[63.444, -16.219, -61.648]} scale={20.171} />
      <mesh name="group1576951165" geometry={nodes.group1576951165.geometry} material={materials['mat12.001']} position={[-11.811, -2.514, 73.928]} scale={20.171} />
      <mesh name="group1576951165001" geometry={nodes.group1576951165001.geometry} material={materials['mat12.001']} position={[-48.31, -0.767, 132.244]} scale={20.171} />
      <mesh name="group1576951165002" geometry={nodes.group1576951165002.geometry} material={materials['mat12.001']} position={[63.444, -16.219, -61.648]} scale={20.171} />
    </group>
  )
}

useGLTF.preload('./models/world/split/ChristmasStuff.glb')
