/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Church.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Church.glb')
  return (
    <group {...props} dispose={null}>
      <group name="church" position={[-145.93, -4.48, -77.977]} rotation={[-0.076, 0.753, 0.051]}>
        <mesh name="Scene028" geometry={nodes.Scene028.geometry} material={materials.Wood} />
        <mesh name="Scene028_1" geometry={nodes.Scene028_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene028_2" geometry={nodes.Scene028_2.geometry} material={materials.Wood_Light} />
        <mesh name="Scene028_3" geometry={nodes.Scene028_3.geometry} material={materials.Plaster} />
        <mesh name="Scene028_4" geometry={nodes.Scene028_4.geometry} material={materials['light_wood_01.001']} />
        <mesh name="Scene028_5" geometry={nodes.Scene028_5.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene028_6" geometry={nodes.Scene028_6.geometry} material={materials['pine_trunk.001']} />
        <mesh name="Scene028_7" geometry={nodes.Scene028_7.geometry} material={materials['rock_dark.001']} />
        <mesh name="Scene028_8" geometry={nodes.Scene028_8.geometry} material={materials['window_01_nightlight.010']} />
      </group>
      <group name="fence_snowy_02" position={[-141.705, -3.668, -69.058]} rotation={[0.136, 0.653, -0.057]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02001" position={[-138.231, -3.914, -63.576]} rotation={[3.06, -0.618, -3.121]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02002" position={[-138.247, -3.547, -75.155]} rotation={[0.001, 0.791, -0.066]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02003" position={[-135.135, -3.532, -71.714]} rotation={[0.059, 0.71, -0.058]}>
        <mesh name="Scene048" geometry={nodes.Scene048.geometry} material={materials.DarkWood} />
        <mesh name="Scene048_1" geometry={nodes.Scene048_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene048_2" geometry={nodes.Scene048_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_02004" position={[-132.575, -3.514, -68.028]} rotation={[0.059, 0.71, -0.058]}>
        <mesh name="Scene001" geometry={nodes.Scene001.geometry} material={materials.DarkWood} />
        <mesh name="Scene001_1" geometry={nodes.Scene001_1.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene001_2" geometry={nodes.Scene001_2.geometry} material={materials.Wood_Light} />
      </group>
      <group name="fence_snowy_03" position={[-139.739, -4.052, -66.408]} rotation={[0.069, 0.294, 0.047]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="fence_snowy_03001" position={[-130.948, -4.318, -65.64]} rotation={[0.08, 0.294, -0.084]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="snowman_01" position={[-139.11, -5.191, -58.586]} rotation={[0.089, 0.294, -0.163]}>
        <mesh name="Scene046" geometry={nodes.Scene046.geometry} material={materials['black matte']} />
        <mesh name="Scene046_1" geometry={nodes.Scene046_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene046_2" geometry={nodes.Scene046_2.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene046_3" geometry={nodes.Scene046_3.geometry} material={materials['pine_trunk.001']} />
        <mesh name="Scene046_4" geometry={nodes.Scene046_4.geometry} material={materials['rock_dark.001']} />
      </group>
      <group name="streetlamp_01" position={[-144.345, -4.339, -68.189]} rotation={[0.113, 0.293, -0.007]}>
        <mesh name="Scene049" geometry={nodes.Scene049.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene049_1" geometry={nodes.Scene049_1.geometry} material={materials['rock_dark.001']} />
        <mesh name="Scene049_2" geometry={nodes.Scene049_2.geometry} material={materials['window_01_nightlight.010']} />
      </group>
      <group name="streetlamp_02" position={[-136.115, -4.097, -75.845]} rotation={[0.001, 0.295, -0.066]}>
        <mesh name="Scene044" geometry={nodes.Scene044.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene044_1" geometry={nodes.Scene044_1.geometry} material={materials['rock_dark.001']} />
        <mesh name="Scene044_2" geometry={nodes.Scene044_2.geometry} material={materials['window_01_nightlight.010']} />
      </group>
      <mesh name="rock_group_01" geometry={nodes.rock_group_01.geometry} material={materials['rock_dark.001']} position={[-156.22, -5.965, -75.176]} rotation={[-0.153, 0.291, 0.201]} />
      <mesh name="rock_group_02" geometry={nodes.rock_group_02.geometry} material={materials['rock_dark.001']} position={[-119.839, -5.385, -65.172]} rotation={[0.003, 0.295, 0.035]} />
      <mesh name="rock_group_02001" geometry={nodes.rock_group_02001.geometry} material={materials['rock_dark.001']} position={[-152.864, -5.362, -68.854]} rotation={[-0.16, 0.291, 0.198]} />
      <mesh name="rock_group_03" geometry={nodes.rock_group_03.geometry} material={materials['rock_dark.001']} position={[-139.958, -5.384, -89.468]} rotation={[0.154, 0.291, -0.005]} />
      <mesh name="rock_group_03001" geometry={nodes.rock_group_03001.geometry} material={materials['rock_dark.001']} position={[-158.299, -5.967, -71.183]} rotation={[-0.16, 0.291, 0.198]} />
      <mesh name="rock_group_04" geometry={nodes.rock_group_04.geometry} material={materials['rock_dark.001']} position={[-138.168, -5.37, -52.215]} rotation={[0.028, 0.295, -0.098]} />
      <mesh name="snow_pile_01" geometry={nodes.snow_pile_01.geometry} material={materials['ground_snow.001']} position={[-128.871, -4.967, -75.424]} rotation={[-0.015, 0.295, -0.001]} />
    </group>
  )
}

useGLTF.preload('./models/world/split/Church.glb')
