/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Cliffs.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Cliffs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="cliff_02020" geometry={nodes.cliff_02020.geometry} material={materials['rock_dark.001']} position={[50.766, -8.797, 79.5]} rotation={[-0.431, 0.05, -0.11]} />
      <mesh name="cliff_02" geometry={nodes.cliff_02.geometry} material={materials['rock_dark.001']} position={[-30.732, -10.333, 33.172]} rotation={[-2.135, 1.105, 2.332]} />
      <mesh name="cliff_02002" geometry={nodes.cliff_02002.geometry} material={materials['rock_dark.001']} position={[-28.373, -8.919, -0.119]} rotation={[-0.448, 0.505, 0.373]} />
      <mesh name="cliff_02004" geometry={nodes.cliff_02004.geometry} material={materials['rock_dark.001']} position={[15.135, -4.424, -12.999]} rotation={[0.53, 0.062, -2.989]} />
      <mesh name="cliff_02006" geometry={nodes.cliff_02006.geometry} material={materials['rock_dark.001']} position={[33.778, -5.067, 18.753]} rotation={[0.929, -0.889, -2.149]} />
      <mesh name="cliff_02008" geometry={nodes.cliff_02008.geometry} material={materials['rock_dark.001']} position={[50.087, -4.905, 65.956]} rotation={[1.16, -1.377, 1.266]} />
      <mesh name="cliff_02009" geometry={nodes.cliff_02009.geometry} material={materials['rock_dark.001']} position={[33.333, -15.187, 11.108]} rotation={[-0.015, -0.214, 0.402]} />
      <mesh name="cliff_02010" geometry={nodes.cliff_02010.geometry} material={materials['rock_dark.001']} position={[68.442, -17.324, 32.389]} rotation={[0.12, -0.213, -0.07]} scale={[1, 1, 1.7]} />
      <mesh name="cliff_02019" geometry={nodes.cliff_02019.geometry} material={materials['rock_dark.001']} position={[9.842, -4.271, -48.882]} rotation={[0.006, -0.214, 0.156]} />
      <mesh name="cliff_01" geometry={nodes.cliff_01.geometry} material={materials['rock_dark.001']} position={[-26.781, -6.349, 32.325]} rotation={[-0.094, -0.22, -2.518]} />
      <mesh name="cliff_01002" geometry={nodes.cliff_01002.geometry} material={materials['rock_dark.001']} position={[-26.438, -4.935, 3.428]} rotation={[-0.942, -1.457, 2.847]} />
      <mesh name="cliff_01004" geometry={nodes.cliff_01004.geometry} material={materials['rock_dark.001']} position={[15.684, -8.924, -9.587]} rotation={[-3.126, 1.03, -2.404]} />
      <mesh name="cliff_01006" geometry={nodes.cliff_01006.geometry} material={materials['rock_dark.001']} position={[30.814, -9.567, 20.531]} rotation={[-0.013, 0.921, 0.762]} />
      <mesh name="cliff_01008" geometry={nodes.cliff_01008.geometry} material={materials['rock_dark.001']} position={[49.634, -8.46, 62.227]} rotation={[1.256, -1.1, -0.125]} />
      <mesh name="cliff_01009" geometry={nodes.cliff_01009.geometry} material={materials['rock_dark.001']} position={[38.046, -14.031, 17.256]} rotation={[0.222, -0.209, -0.071]} />
      <mesh name="cliff_01010" geometry={nodes.cliff_01010.geometry} material={materials['rock_dark.001']} position={[33.248, -14.409, -3.546]} rotation={[-0.127, -0.212, -0.118]} />
      <mesh name="cliff_01011" geometry={nodes.cliff_01011.geometry} material={materials['rock_dark.001']} position={[66.693, -17.001, 13.943]} rotation={[-0.031, -0.214, -0.017]} />
      <mesh name="cliff_01001" geometry={nodes.cliff_01001.geometry} material={materials['rock_dark.001']} position={[-32.761, -5.701, 25.893]} rotation={[-2.896, 1.185, 0.416]} />
      <mesh name="cliff_01003" geometry={nodes.cliff_01003.geometry} material={materials['rock_dark.001']} position={[-21.971, -4.287, -4.134]} rotation={[-0.116, 0.66, -2.426]} />
      <mesh name="cliff_01005" geometry={nodes.cliff_01005.geometry} material={materials['rock_dark.001']} position={[7.732, -9.286, -13.355]} rotation={[0.236, -0.055, 0.68]} />
      <mesh name="cliff_01007" geometry={nodes.cliff_01007.geometry} material={materials['rock_dark.001']} position={[31.356, -9.928, 11.748]} rotation={[0.646, -1.172, 1.275]} />
      <mesh name="cliff_02001" geometry={nodes.cliff_02001.geometry} material={materials['rock_dark.001']} position={[-29.842, -9.685, 28.686]} rotation={[-2.582, -0.776, -2.583]} />
      <mesh name="cliff_02003" geometry={nodes.cliff_02003.geometry} material={materials['rock_dark.001']} position={[-23.819, -8.271, -0.541]} rotation={[-2.719, 0.39, 3.117]} />
      <mesh name="cliff_02005" geometry={nodes.cliff_02005.geometry} material={materials['rock_dark.001']} position={[11.171, -5.506, -10.888]} rotation={[2.583, -0.896, -0.456]} />
      <mesh name="cliff_02007" geometry={nodes.cliff_02007.geometry} material={materials['rock_dark.001']} position={[30.344, -6.149, 15.858]} rotation={[2.797, 0.203, 0.07]} />
      <mesh name="cliff_group_01" geometry={nodes.cliff_group_01.geometry} material={materials['rock_dark.001']} position={[-14.716, -12.217, 39.751]} rotation={[-3.058, 0.623, -2.769]} />
      <mesh name="cliff_group_01002" geometry={nodes.cliff_group_01002.geometry} material={materials['rock_dark.001']} position={[-30.127, -10.804, 17.107]} rotation={[-0.202, 1.228, 0.612]} />
      <mesh name="cliff_group_01004" geometry={nodes.cliff_group_01004.geometry} material={materials['rock_dark.001']} position={[26.313, -4.09, 0.353]} rotation={[0.248, -0.625, -2.634]} />
      <mesh name="cliff_group_01006" geometry={nodes.cliff_group_01006.geometry} material={materials['rock_dark.001']} position={[28.323, -6.674, 35.281]} rotation={[1.556, -1.37, -1.225]} scale={[1.88, 1.75, 1]} />
      <mesh name="cliff_group_01058" geometry={nodes.cliff_group_01058.geometry} material={materials['rock_dark.001']} position={[42.496, -5.541, 47.522]} rotation={[-1.34, -0.826, 2.54]} scale={[1.82, 1, 2.03]} />
      <mesh name="cliff_group_01008" geometry={nodes.cliff_group_01008.geometry} material={materials['rock_dark.001']} position={[51.502, -9.809, 46.737]} rotation={[0.849, -1.479, 1.086]} />
      <mesh name="cliff_group_01009" geometry={nodes.cliff_group_01009.geometry} material={materials['rock_dark.001']} position={[50.708, -11.04, 40.215]} rotation={[-2.997, 1.316, 2.838]} />
      <mesh name="cliff_group_01010" geometry={nodes.cliff_group_01010.geometry} material={materials['rock_dark.001']} position={[39.275, -16.042, 22.374]} rotation={[-0.272, -0.467, 0.186]} />
      <mesh name="cliff_group_01011" geometry={nodes.cliff_group_01011.geometry} material={materials['rock_dark.001']} position={[27.428, -14.164, -16.439]} rotation={[-0.355, -0.918, -0.18]} />
      <mesh name="cliff_group_01012" geometry={nodes.cliff_group_01012.geometry} material={materials['rock_dark.001']} position={[70.082, -15.218, 62.992]} rotation={[1.038, -1.082, 1.264]} />
      <mesh name="cliff_group_01013" geometry={nodes.cliff_group_01013.geometry} material={materials['rock_dark.001']} position={[74.469, -17.708, 77.329]} rotation={[0.559, -0.65, 0.468]} />
      <mesh name="cliff_group_01015" geometry={nodes.cliff_group_01015.geometry} material={materials['rock_dark.001']} position={[68.053, -15.156, 55.404]} rotation={[0.014, 1.413, 0.05]} />
      <mesh name="cliff_group_01014" geometry={nodes.cliff_group_01014.geometry} material={materials['rock_dark.001']} position={[7.842, -9.896, -54.131]} rotation={[-1.538, -0.349, -2.927]} />
      <mesh name="cliff_group_01044" geometry={nodes.cliff_group_01044.geometry} material={materials['rock_dark.001']} position={[8.871, -16.296, -53.676]} rotation={[-0.192, -0.21, 0.377]} scale={[1, 1, 5.56]} />
      <mesh name="cliff_group_01050" geometry={nodes.cliff_group_01050.geometry} material={materials['rock_dark.001']} position={[30.031, -6.15, -33.184]} rotation={[0.375, -0.402, -0.822]} scale={0.467} />
      <mesh name="cliff_group_01001" geometry={nodes.cliff_group_01001.geometry} material={materials['rock_dark.001']} position={[-33.394, -11.569, 11.74]} rotation={[-1.964, -1.498, -1.544]} />
      <mesh name="cliff_group_01003" geometry={nodes.cliff_group_01003.geometry} material={materials['rock_dark.001']} position={[-9.585, -16.567, -12.498]} rotation={[-3.072, -0.26, -2.703]} />
      <mesh name="cliff_group_01005" geometry={nodes.cliff_group_01005.geometry} material={materials['rock_dark.001']} position={[-7.091, -10.848, -12.545]} rotation={[-3.082, -0.342, 0.364]} />
      <mesh name="cliff_group_01007" geometry={nodes.cliff_group_01007.geometry} material={materials['rock_dark.001']} position={[22, -5.079, 0.608]} rotation={[-3.056, 0.846, 0.28]} />
      <mesh name="cliff_03" geometry={nodes.cliff_03.geometry} material={materials['rock_dark.001']} position={[51.459, -7.263, 72.776]} rotation={[-0.431, 0.05, -0.11]} />
      <mesh name="cliff_03001" geometry={nodes.cliff_03001.geometry} material={materials['rock_dark.001']} position={[31.865, -15.03, 6.526]} rotation={[0.274, -0.206, 0.144]} />
      <mesh name="cliff_03002" geometry={nodes.cliff_03002.geometry} material={materials['rock_dark.001']} position={[34.406, -14.847, 1.281]} rotation={[-0.047, -0.214, 0.162]} />
      <mesh name="cliff_03003" geometry={nodes.cliff_03003.geometry} material={materials['rock_dark.001']} position={[71.857, -10.926, 78.888]} rotation={[-2.084, -1.53, -0.955]} />
      <mesh name="cliff_03004" geometry={nodes.cliff_03004.geometry} material={materials['rock_dark.001']} position={[71.829, -15.572, 39.258]} rotation={[2.214, 0.383, -0.089]} />
      <mesh name="cliff_03005" geometry={nodes.cliff_03005.geometry} material={materials['rock_dark.001']} position={[67.333, -18.04, 22.562]} rotation={[-2.768, -0.093, -2.967]} scale={[1, 1, 2.23]} />
      <mesh name="cliff_03006" geometry={nodes.cliff_03006.geometry} material={materials['rock_dark.001']} position={[16.974, -7.258, -26.429]} rotation={[-0.871, -0.157, -0.524]} />
      {/* <mesh name="cliff_03007" geometry={nodes.cliff_03007.geometry} material={materials['rock_dark.001']} position={[35.103, -9.764, -21.68]} rotation={[1.389, -0.131, -1.051]} /> */}
      <mesh name="cliff_group_01021" geometry={nodes.cliff_group_01021.geometry} material={materials['rock_dark.001']} position={[-1.113, -22.66, -56.962]} rotation={[-3.122, -0.519, -2.66]} />
      <mesh name="cliff_group_01033" geometry={nodes.cliff_group_01033.geometry} material={materials['rock_dark.001']} position={[143.366, -22.826, -25.164]} rotation={[-0.147, 1.457, 0.619]} />
      <mesh name="cliff_group_01022" geometry={nodes.cliff_group_01022.geometry} material={materials['rock_dark.001']} position={[-12.268, -20.016, -27.188]} rotation={[-0.706, 1.423, 0.848]} />
      <mesh name="cliff_02011" geometry={nodes.cliff_02011.geometry} material={materials['rock_dark.001']} position={[-11.999, -20.273, -46.766]} rotation={[-2.821, 0.157, -3.041]} />
      <mesh name="cliff_02012" geometry={nodes.cliff_02012.geometry} material={materials['rock_dark.001']} position={[-14.185, -21.555, -42.885]} rotation={[-0.592, 0.747, 0.502]} />
      <mesh name="cliff_01012" geometry={nodes.cliff_01012.geometry} material={materials['rock_dark.001']} position={[-11.711, -17.268, -50.631]} rotation={[-0.196, 0.923, -2.408]} scale={[1, 2.19, 2.01]} />
      <mesh name="cliff_01013" geometry={nodes.cliff_01013.geometry} material={materials['rock_dark.001']} position={[-11.773, -16.38, -41.587]} rotation={[-0.399, -1.224, -2.814]} />
      <mesh name="cliff_01014" geometry={nodes.cliff_01014.geometry} material={materials['rock_dark.001']} position={[2.099, -17.193, -60.887]} rotation={[-0.21, 0.887, -2.273]} />
      <mesh name="cliff_01022" geometry={nodes.cliff_01022.geometry} material={materials['rock_dark.001']} position={[144.639, -17.359, -20.254]} rotation={[-0.468, -1.274, -2.887]} />
      <mesh name="cliff_01015" geometry={nodes.cliff_01015.geometry} material={materials['rock_dark.001']} position={[18.231, -17.499, -74.716]} rotation={[-0.25, 1.009, -2.224]} />
      <mesh name="cliff_01023" geometry={nodes.cliff_01023.geometry} material={materials['rock_dark.001']} position={[146.277, -15.217, 0.931]} rotation={[-0.335, -1.158, -2.746]} />
      <mesh name="cliff_01016" geometry={nodes.cliff_01016.geometry} material={materials['rock_dark.001']} position={[51.275, -15.437, -88.308]} rotation={[-0.155, 0.55, -2.355]} />
      <mesh name="cliff_01024" geometry={nodes.cliff_01024.geometry} material={materials['rock_dark.001']} position={[137.741, -15.603, 35.627]} rotation={[-2.091, -1.418, 1.751]} />
      <mesh name="cliff_01017" geometry={nodes.cliff_01017.geometry} material={materials['rock_dark.001']} position={[87.446, -14.838, -86.767]} rotation={[-3.009, -0.065, 0.713]} />
      <mesh name="cliff_01025" geometry={nodes.cliff_01025.geometry} material={materials['rock_dark.001']} position={[115.144, -15.004, 63.912]} rotation={[-0.243, 0.991, -2.232]} />
      <mesh name="cliff_01018" geometry={nodes.cliff_01018.geometry} material={materials['rock_dark.001']} position={[118.218, -12.89, -68.235]} rotation={[-3.004, 0.267, 0.668]} />
      <mesh name="cliff_01026" geometry={nodes.cliff_01026.geometry} material={materials['rock_dark.001']} position={[82.02, -13.056, 77.81]} rotation={[-0.168, 0.663, -2.333]} />
      <mesh name="cliff_01019" geometry={nodes.cliff_01019.geometry} material={materials['rock_dark.001']} position={[137.479, -12.89, -39.451]} rotation={[-2.895, 0.999, 0.497]} />
      <mesh name="cliff_02013" geometry={nodes.cliff_02013.geometry} material={materials['rock_dark.001']} position={[2.326, -22.368, -58.158]} rotation={[-2.715, 0.141, -3.131]} />
      <mesh name="cliff_02021" geometry={nodes.cliff_02021.geometry} material={materials['rock_dark.001']} position={[142.301, -22.534, -21.683]} rotation={[-0.565, 0.701, 0.462]} />
      <mesh name="cliff_02014" geometry={nodes.cliff_02014.geometry} material={materials['rock_dark.001']} position={[18.798, -22.674, -72.036]} rotation={[-2.72, 0.027, -3.079]} />
      <mesh name="cliff_02022" geometry={nodes.cliff_02022.geometry} material={materials['rock_dark.001']} position={[143.78, -20.392, -0.194]} rotation={[-0.632, 0.804, 0.559]} />
      <mesh name="cliff_02015" geometry={nodes.cliff_02015.geometry} material={materials['rock_dark.001']} position={[50.572, -20.612, -85.661]} rotation={[-2.669, 0.45, 2.997]} />
      <mesh name="cliff_02023" geometry={nodes.cliff_02023.geometry} material={materials['rock_dark.001']} position={[136.019, -20.778, 33.496]} rotation={[-0.461, 0.401, 0.265]} />
      <mesh name="cliff_02016" geometry={nodes.cliff_02016.geometry} material={materials['rock_dark.001']} position={[89.312, -20.013, -88.772]} rotation={[-0.684, -0.865, -0.481]} />
      <mesh name="cliff_02024" geometry={nodes.cliff_02024.geometry} material={materials['rock_dark.001']} position={[115.66, -20.179, 66.602]} rotation={[-2.719, 0.044, -3.087]} />
      <mesh name="cliff_02017" geometry={nodes.cliff_02017.geometry} material={materials['rock_dark.001']} position={[120.64, -18.065, -69.515]} rotation={[-1.07, -1.085, -0.942]} />
      <mesh name="cliff_02025" geometry={nodes.cliff_02025.geometry} material={materials['rock_dark.001']} position={[81.623, -18.231, 80.52]} rotation={[-2.691, 0.348, 3.052]} />
      <mesh name="cliff_02018" geometry={nodes.cliff_02018.geometry} material={materials['rock_dark.001']} position={[140.129, -18.065, -38.756]} rotation={[-2.384, -0.932, -2.418]} />
      <mesh name="cliff_group_01023" geometry={nodes.cliff_group_01023.geometry} material={materials['rock_dark.001']} position={[14.442, -20.829, -68.319]} rotation={[-3.034, -0.461, -2.946]} />
      <mesh name="cliff_group_01035" geometry={nodes.cliff_group_01035.geometry} material={materials['rock_dark.001']} position={[143.351, -18.547, -5.904]} rotation={[-0.522, 1.377, 0.661]} />
      <mesh name="cliff_group_01024" geometry={nodes.cliff_group_01024.geometry} material={materials['rock_dark.001']} position={[29.546, -21.135, -83.636]} rotation={[-3.026, -0.586, -2.93]} />
      <mesh name="cliff_group_01036" geometry={nodes.cliff_group_01036.geometry} material={materials['rock_dark.001']} position={[146.523, -20.209, 15.213]} rotation={[-1.153, 1.466, 1.299]} />
      <mesh name="cliff_group_01025" geometry={nodes.cliff_group_01025.geometry} material={materials['rock_dark.001']} position={[65.398, -19.073, -91.16]} rotation={[-3.045, -0.12, -2.982]} />
      <mesh name="cliff_group_01037" geometry={nodes.cliff_group_01037.geometry} material={materials['rock_dark.001']} position={[131.706, -19.239, 48.71]} rotation={[-0.194, 1.052, 0.317]} />
      <mesh name="cliff_group_01026" geometry={nodes.cliff_group_01026.geometry} material={materials['rock_dark.001']} position={[45.007, -18.767, -84.31]} rotation={[-3.046, 0.005, -2.995]} />
      <mesh name="cliff_group_01038" geometry={nodes.cliff_group_01038.geometry} material={materials['rock_dark.001']} position={[138.214, -18.933, 28.207]} rotation={[-0.161, 0.928, 0.276]} />
      <mesh name="cliff_group_01027" geometry={nodes.cliff_group_01027.geometry} material={materials['rock_dark.001']} position={[94.858, -18.168, -87.346]} rotation={[-0.109, -0.492, 0.096]} />
      <mesh name="cliff_group_01039" geometry={nodes.cliff_group_01039.geometry} material={materials['rock_dark.001']} position={[111.235, -18.334, 70.236]} rotation={[-3.035, -0.442, -2.948]} />
      <mesh name="cliff_group_01028" geometry={nodes.cliff_group_01028.geometry} material={materials['rock_dark.001']} position={[73.642, -18.474, -90.896]} rotation={[-0.103, -0.368, 0.11]} />
      <mesh name="cliff_group_01040" geometry={nodes.cliff_group_01040.geometry} material={materials['rock_dark.001']} position={[126.625, -18.64, 55.207]} rotation={[-3.028, -0.567, -2.933]} />
      <mesh name="cliff_group_01029" geometry={nodes.cliff_group_01029.geometry} material={materials['rock_dark.001']} position={[106.54, -16.526, -76.674]} rotation={[-0.126, -0.701, 0.066]} />
      <mesh name="cliff_group_01041" geometry={nodes.cliff_group_01041.geometry} material={materials['rock_dark.001']} position={[95.725, -16.692, 73.366]} rotation={[-3.043, -0.234, -2.971]} />
      <mesh name="cliff_group_01030" geometry={nodes.cliff_group_01030.geometry} material={materials['rock_dark.001']} position={[125.408, -16.22, -66.344]} rotation={[-0.142, -0.825, 0.043]} />
      <mesh name="cliff_group_01031" geometry={nodes.cliff_group_01031.geometry} material={materials['rock_dark.001']} position={[141.496, -16.22, -33.196]} rotation={[-1.592, -1.475, -1.444]} />
      <mesh name="cliff_group_01032" geometry={nodes.cliff_group_01032.geometry} material={materials['rock_dark.001']} position={[134.584, -16.526, -53.566]} rotation={[-0.663, -1.415, -0.51]} />
      <mesh name="cliff_group_01017" geometry={nodes.cliff_group_01017.geometry} material={materials['rock_dark.001']} position={[13.401, -15.481, -21.865]} rotation={[-0.215, -0.14, 0.076]} />
      <mesh name="cliff_group_01018" geometry={nodes.cliff_group_01018.geometry} material={materials['rock_dark.001']} position={[-5.138, -16.432, -21.633]} rotation={[3.12, -0.122, -0.107]} />
      <mesh name="cliff_group_01019" geometry={nodes.cliff_group_01019.geometry} material={materials['rock_dark.001']} position={[-2.364, -16.284, -21.749]} rotation={[-0.214, 0.099, 0.128]} />
      <mesh name="cliff_group_01020" geometry={nodes.cliff_group_01020.geometry} material={materials['rock_dark.001']} position={[-18.428, -18.879, -18.596]} rotation={[3.12, -0.122, -0.107]} />
      <mesh name="cliff_group_01016" geometry={nodes.cliff_group_01016.geometry} material={materials['rock_dark.001']} position={[-6.653, -12.525, -46.371]} rotation={[-1.352, 0.045, 0.069]} />
      <mesh name="cliff_group_01034" geometry={nodes.cliff_group_01034.geometry} material={materials['rock_dark.001']} position={[-6.042, -11.535, -37.695]} rotation={[1.158, 0.2, 0.23]} />
      <mesh name="cliff_group_01042" geometry={nodes.cliff_group_01042.geometry} material={materials['rock_dark.001']} position={[-10.061, -12.028, -29.011]} rotation={[1.612, 0.282, -0.055]} />
      <mesh name="cliff_group_01043" geometry={nodes.cliff_group_01043.geometry} material={materials['rock_dark.001']} position={[13.151, -6.812, -35.012]} rotation={[-1.543, -0.142, -2.647]} />
      <mesh name="cliff_group_01045" geometry={nodes.cliff_group_01045.geometry} material={materials['rock_dark.001']} position={[18.285, -14.718, -48.294]} rotation={[-0.192, -0.21, 0.377]} scale={[1, 1.253, 1.657]} />
      <mesh name="cliff_group_01046" geometry={nodes.cliff_group_01046.geometry} material={materials['rock_dark.001']} position={[26.308, -17.068, -43.142]} rotation={[-0.364, -1.02, 0.104]} />
      <mesh name="cliff_group_01047" geometry={nodes.cliff_group_01047.geometry} material={materials['rock_dark.001']} position={[20.214, -9.789, -43.537]} rotation={[-2.309, 0.389, -0.973]} />
      <mesh name="cliff_group_01048" geometry={nodes.cliff_group_01048.geometry} material={materials['rock_dark.001']} position={[14.165, -7.017, -46.869]} rotation={[-1.573, -0.617, -2.291]} />
      <mesh name="cliff_group_01049" geometry={nodes.cliff_group_01049.geometry} material={materials['rock_dark.001']} position={[13.729, -6.402, -27.025]} rotation={[-1.643, 0.126, 0.824]} />
      <mesh name="cliff_group_01051" geometry={nodes.cliff_group_01051.geometry} material={materials['rock_dark.001']} position={[33.434, -12.139, -31.5]} rotation={[-0.212, -0.604, -1.385]} scale={0.467} />
      <mesh name="cliff_group_01052" geometry={nodes.cliff_group_01052.geometry} material={materials['rock_dark.001']} position={[34.33, -18.095, -30.763]} rotation={[-0.17, -0.861, 0.123]} scale={0.467} />
      <mesh name="cliff_group_01053" geometry={nodes.cliff_group_01053.geometry} material={materials['rock_dark.001']} position={[35.321, -12.977, -27.998]} rotation={[-0.17, -0.861, 0.123]} scale={[0.467, 0.747, 0.467]} />
      <mesh name="cliff_group_01054" geometry={nodes.cliff_group_01054.geometry} material={materials['rock_dark.001']} position={[35.321, -12.977, -27.998]} rotation={[-0.17, -0.861, 0.123]} scale={0.467} />
      <mesh name="cliff_group_01055" geometry={nodes.cliff_group_01055.geometry} material={materials['rock_dark.001']} position={[27.79, -7.9, -21.093]} rotation={[1.398, 0.006, 0.708]} scale={0.467} />
      <mesh name="cliff_group_01056" geometry={nodes.cliff_group_01056.geometry} material={materials['rock_dark.001']} position={[22.494, -7.406, -24.899]} rotation={[1.398, 0.006, 0.708]} scale={0.467} />
      <mesh name="cliff_group_01057" geometry={nodes.cliff_group_01057.geometry} material={materials['rock_dark.001']} position={[27.26, -8.137, -28.907]} rotation={[1.398, 0.006, 0.708]} scale={[0.877, 0.927, 0.467]} />
      <mesh name="rock_small_01001" geometry={nodes.rock_small_01001.geometry} material={materials['rock_dark.001']} position={[9.325, -15.85, -45.452]} rotation={[-0.39, -0.198, -2.966]} />
      <mesh name="rock_small_01002" geometry={nodes.rock_small_01002.geometry} material={materials['rock_dark.001']} position={[-13.618, -24.688, -45.954]} rotation={[1.748, -0.68, -1.232]} />
      <mesh name="rock_small_01003" geometry={nodes.rock_small_01003.geometry} material={materials['rock_dark.001']} position={[-1.436, -15.269, -55.616]} rotation={[-2.061, 1.125, -1.15]} scale={[2.32, 1.18, 1.75]} />
      <mesh name="rock_small_01004" geometry={nodes.rock_small_01004.geometry} material={materials['rock_dark.001']} position={[-13.17, -15.361, -47.255]} rotation={[2.894, -0.962, 1.425]} />
      <mesh name="rock_medium_02" geometry={nodes.rock_medium_02.geometry} material={materials['rock_dark.001']} position={[20.615, -20.077, -50.969]} rotation={[-0.746, -0.506, 0.936]} />
      <mesh name="rock_medium_02001" geometry={nodes.rock_medium_02001.geometry} material={materials['rock_dark.001']} position={[-9.94, -24.121, -49.771]} rotation={[-0.418, -0.196, -2.501]} />
    </group>
  )
}

useGLTF.preload('./models/world/split/Cliffs.glb')
