/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Cliffs.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Cliffs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="cliff_02020" geometry={nodes.cliff_02020.geometry} material={materials['rock_dark.001']} position={[-91.261, -8.797, 33.343]} rotation={[-1.991, -1.096, -2.17]} />
      <mesh name="cliff_02" geometry={nodes.cliff_02.geometry} material={materials['rock_dark.001']} position={[-25.376, -10.333, -33.345]} rotation={[-0.389, 0, 0.144]} />
      <mesh name="cliff_02002" geometry={nodes.cliff_02002.geometry} material={materials['rock_dark.001']} position={[6.163, -8.919, -22.431]} rotation={[-0.964, -1.091, -0.763]} />
      <mesh name="cliff_02004" geometry={nodes.cliff_02004.geometry} material={materials['rock_dark.001']} position={[7.315, -4.424, 22.929]} rotation={[1.884, -1.011, -1.017]} />
      <mesh name="cliff_02006" geometry={nodes.cliff_02006.geometry} material={materials['rock_dark.001']} position={[-28.186, -5.067, 32.696]} rotation={[2.604, -0.164, 0.092]} />
      <mesh name="cliff_02008" geometry={nodes.cliff_02008.geometry} material={materials['rock_dark.001']} position={[-78.005, -4.905, 36.201]} rotation={[2.962, 0.181, -2.995]} />
      <mesh name="cliff_02009" geometry={nodes.cliff_02009.geometry} material={materials['rock_dark.001']} position={[-20.688, -15.187, 34.249]} rotation={[-3.11, -1.094, -2.708]} />
      <mesh name="cliff_02010" geometry={nodes.cliff_02010.geometry} material={materials['rock_dark.001']} position={[-50.349, -17.324, 62.636]} rotation={[2.889, -1.081, 2.823]} scale={[1, 1, 1.7]} />
      <mesh name="cliff_02019" geometry={nodes.cliff_02019.geometry} material={materials['rock_dark.001']} position={[43.342, -4.271, 27.127]} rotation={[3.129, -1.094, -2.999]} />
      <mesh name="cliff_01" geometry={nodes.cliff_01.geometry} material={materials['rock_dark.001']} position={[-25.583, -6.349, -29.31]} rotation={[-2.947, -1.079, 0.817]} />
      <mesh name="cliff_01002" geometry={nodes.cliff_01002.geometry} material={materials['rock_dark.001']} position={[2.236, -4.935, -21.482]} rotation={[-3.048, 0.195, 0.626]} />
      <mesh name="cliff_01004" geometry={nodes.cliff_01004.geometry} material={materials['rock_dark.001']} position={[3.877, -8.924, 22.574]} rotation={[-0.008, 0.278, 0.753]} />
      <mesh name="cliff_01006" geometry={nodes.cliff_01006.geometry} material={materials['rock_dark.001']} position={[-29.135, -9.567, 29.372]} rotation={[-0.013, -0.912, 0.741]} />
      <mesh name="cliff_01008" geometry={nodes.cliff_01008.geometry} material={materials['rock_dark.001']} position={[-74.286, -8.46, 36.731]} rotation={[2.693, 0.096, 1.842]} />
      <mesh name="cliff_01009" geometry={nodes.cliff_01009.geometry} material={materials['rock_dark.001']} position={[-27.848, -14.031, 37.207]} rotation={[2.693, -1.051, 2.628]} />
      <mesh name="cliff_01010" geometry={nodes.cliff_01010.geometry} material={materials['rock_dark.001']} position={[-6.514, -14.409, 37.97]} rotation={[-2.875, -1.079, -2.996]} />
      <mesh name="cliff_01011" geometry={nodes.cliff_01011.geometry} material={materials['rock_dark.001']} position={[-32.081, -17.001, 65.733]} rotation={[-3.075, -1.093, -3.093]} />
      <mesh name="cliff_01001" geometry={nodes.cliff_01001.geometry} material={materials['rock_dark.001']} position={[-17.819, -5.701, -33.417]} rotation={[-0.092, 0.112, -2.487]} />
      <mesh name="cliff_01003" geometry={nodes.cliff_01003.geometry} material={materials['rock_dark.001']} position={[8.38, -4.287, -15.206]} rotation={[-0.231, -1.16, -2.71]} />
      <mesh name="cliff_01005" geometry={nodes.cliff_01005.geometry} material={materials['rock_dark.001']} position={[9.579, -9.286, 15.872]} rotation={[2.488, -1.176, -3.09]} />
      <mesh name="cliff_01007" geometry={nodes.cliff_01007.geometry} material={materials['rock_dark.001']} position={[-20.793, -9.928, 32.174]} rotation={[2.905, -0.06, -2.489]} />
      <mesh name="cliff_02001" geometry={nodes.cliff_02001.geometry} material={materials['rock_dark.001']} position={[-21.274, -9.685, -31.322]} rotation={[-2.511, 0.872, 2.777]} />
      <mesh name="cliff_02003" geometry={nodes.cliff_02003.geometry} material={materials['rock_dark.001']} position={[5.389, -8.271, -17.923]} rotation={[-0.574, 0.798, 0.578]} />
      <mesh name="cliff_02005" geometry={nodes.cliff_02005.geometry} material={materials['rock_dark.001']} position={[6.305, -5.506, 18.553]} rotation={[2.648, 0.796, 0.364]} />
      <mesh name="cliff_02007" geometry={nodes.cliff_02007.geometry} material={materials['rock_dark.001']} position={[-24.5, -6.149, 30.131]} rotation={[0.652, 0.993, 2.57]} />
      <mesh name="cliff_group_01" geometry={nodes.cliff_group_01.geometry} material={materials['rock_dark.001']} position={[-35.884, -12.217, -19.585]} rotation={[-0.087, 0.682, 0.476]} />
      <mesh name="cliff_group_01002" geometry={nodes.cliff_group_01002.geometry} material={materials['rock_dark.001']} position={[-10.017, -10.804, -28.594]} rotation={[-0.082, -0.597, 0.375]} />
      <mesh name="cliff_group_01004" geometry={nodes.cliff_group_01004.geometry} material={materials['rock_dark.001']} position={[-8.48, -4.09, 30.261]} rotation={[2.888, -0.653, 0.204]} />
      <mesh name="cliff_group_01006" geometry={nodes.cliff_group_01006.geometry} material={materials['rock_dark.001']} position={[-42.733, -6.674, 23.14]} rotation={[2.934, 0.254, 0.414]} scale={[1.88, 1.75, 1]} />
      <mesh name="cliff_group_01058" geometry={nodes.cliff_group_01058.geometry} material={materials['rock_dark.001']} position={[-58.232, -5.541, 33.653]} rotation={[-2.42, 0.041, 0.624]} scale={[1.82, 1, 2.03]} />
      <mesh name="cliff_group_01008" geometry={nodes.cliff_group_01008.geometry} material={materials['rock_dark.001']} position={[-59.81, -9.809, 42.554]} rotation={[3.071, 0.201, -2.888]} />
      <mesh name="cliff_group_01009" geometry={nodes.cliff_group_01009.geometry} material={materials['rock_dark.001']} position={[-53.306, -11.04, 43.478]} rotation={[-0.036, -0.011, -0.164]} />
      <mesh name="cliff_group_01010" geometry={nodes.cliff_group_01010.geometry} material={materials['rock_dark.001']} position={[-33.11, -16.042, 37.066]} rotation={[-2.792, -0.795, -2.576]} />
      <mesh name="cliff_group_01011" geometry={nodes.cliff_group_01011.geometry} material={materials['rock_dark.001']} position={[7.448, -14.164, 35.694]} rotation={[-2.915, -0.351, -2.956]} />
      <mesh name="cliff_group_01012" geometry={nodes.cliff_group_01012.geometry} material={materials['rock_dark.001']} position={[-80.329, -15.218, 56.28]} rotation={[2.725, -0.001, -2.861]} />
      <mesh name="cliff_group_01013" geometry={nodes.cliff_group_01013.geometry} material={materials['rock_dark.001']} position={[-95.313, -17.708, 56.798]} rotation={[2.634, -0.518, 2.98]} />
      <mesh name="cliff_group_01015" geometry={nodes.cliff_group_01015.geometry} material={materials['rock_dark.001']} position={[-72.474, -15.156, 56.289]} rotation={[0.002, -0.42, 0.066]} />
      <mesh name="cliff_group_01014" geometry={nodes.cliff_group_01014.geometry} material={materials['rock_dark.001']} position={[48.931, -9.896, 26.557]} rotation={[-1.916, 0.059, 1.527]} />
      <mesh name="cliff_group_01044" geometry={nodes.cliff_group_01044.geometry} material={materials['rock_dark.001']} position={[48.224, -16.296, 27.433]} rotation={[-2.749, -1.061, -2.377]} scale={[1, 1, 5.56]} />
      <mesh name="cliff_group_01050" geometry={nodes.cliff_group_01050.geometry} material={materials['rock_dark.001']} position={[22.945, -6.15, 42.552]} rotation={[2.63, -0.812, 1.78]} scale={0.467} />
      <mesh name="cliff_group_01001" geometry={nodes.cliff_group_01001.geometry} material={materials['rock_dark.001']} position={[-3.986, -11.569, -30.356]} rotation={[-3.071, 0.29, -2.741]} />
      {/* <mesh name="cliff_group_01003" geometry={nodes.cliff_group_01003.geometry} material={materials['rock_dark.001']} position={[9.378, -10.155, -1.074]} rotation={[-1.538, 1.503, 1.958]} /> */}
      {/* <mesh name="cliff_group_01005" geometry={nodes.cliff_group_01005.geometry} material={materials['rock_dark.001']} position={[8.776, -4.437, 1.346]} rotation={[-2.525, 1.473, -0.27]} /> */}
      <mesh name="cliff_group_01007" geometry={nodes.cliff_group_01007.geometry} material={materials['rock_dark.001']} position={[-7.607, -5.079, 26.029]} rotation={[-0.063, 0.46, -2.77]} />
      <mesh name="cliff_03" geometry={nodes.cliff_03.geometry} material={materials['rock_dark.001']} position={[-84.947, -7.263, 35.757]} rotation={[-1.991, -1.096, -2.17]} />
      <mesh name="cliff_03001" geometry={nodes.cliff_03001.geometry} material={materials['rock_dark.001']} position={[-15.882, -15.03, 34.021]} rotation={[2.602, -1.029, 2.754]} />
      <mesh name="cliff_03002" geometry={nodes.cliff_03002.geometry} material={materials['rock_dark.001']} position={[-11.476, -14.847, 37.835]} rotation={[-3.041, -1.092, -2.88]} />
      <mesh name="cliff_03003" geometry={nodes.cliff_03003.geometry} material={materials['rock_dark.001']} position={[-96.142, -10.926, 53.87]} rotation={[-3.104, 0.282, -2.023]} />
      <mesh name="cliff_03004" geometry={nodes.cliff_03004.geometry} material={materials['rock_dark.001']} position={[-57.861, -15.572, 64.125]} rotation={[0.974, 0.456, 2.015]} />
      <mesh name="cliff_03005" geometry={nodes.cliff_03005.geometry} material={materials['rock_dark.001']} position={[-40.57, -18.04, 64.114]} rotation={[-1.178, 1.166, 1.286]} scale={[1, 1, 2.23]} />
      <mesh name="cliff_03006" geometry={nodes.cliff_03006.geometry} material={materials['rock_dark.001']} position={[19.808, -7.258, 28.19]} rotation={[-1.967, -0.611, -2.541]} />
      <mesh name="cliff_03007" geometry={nodes.cliff_03007.geometry} material={materials['rock_dark.001']} position={[10.518, -9.764, 44.466]} rotation={[1.746, -0.14, 0.806]} />
      <mesh name="cliff_group_01021" geometry={nodes.cliff_group_01021.geometry} material={materials['rock_dark.001']} position={[53.988, -22.66, 18.643]} rotation={[-3.076, 1.313, -2.732]} />
      <mesh name="cliff_group_01033" geometry={nodes.cliff_group_01033.geometry} material={materials['rock_dark.001']} position={[-14.204, -22.826, 149.926]} rotation={[-0.018, -0.374, 0.466]} />
      <mesh name="cliff_group_01022" geometry={nodes.cliff_group_01022.geometry} material={materials['rock_dark.001']} position={[28.127, -20.016, 0.146]} rotation={[-0.103, -0.374, 0.11]} />
      <mesh name="cliff_02011" geometry={nodes.cliff_02011.geometry} material={materials['rock_dark.001']} position={[46.966, -20.273, 5.485]} rotation={[-0.669, 1.045, 0.752]} />
      <mesh name="cliff_02012" geometry={nodes.cliff_02012.geometry} material={materials['rock_dark.001']} position={[43.784, -21.555, 2.367]} rotation={[-0.688, -0.87, -0.487]} />
      <mesh name="cliff_01012" geometry={nodes.cliff_01012.geometry} material={materials['rock_dark.001']} position={[50.623, -17.268, 6.766]} rotation={[-0.189, -0.893, -2.713]} scale={[1, 2.19, 2.01]} />
      <mesh name="cliff_01013" geometry={nodes.cliff_01013.geometry} material={materials['rock_dark.001']} position={[41.905, -16.38, 4.36]} rotation={[-3.009, -0.059, 0.713]} />
      <mesh name="cliff_01014" geometry={nodes.cliff_01014.geometry} material={materials['rock_dark.001']} position={[56.946, -17.193, 22.763]} rotation={[-0.221, -0.924, -2.614]} />
      <mesh name="cliff_01022" geometry={nodes.cliff_01022.geometry} material={materials['rock_dark.001']} position={[-19.276, -17.359, 149.881]} rotation={[-3.009, -0.004, 0.705]} />
      <mesh name="cliff_01015" geometry={nodes.cliff_01015.geometry} material={materials['rock_dark.001']} position={[66.116, -17.499, 41.931]} rotation={[-0.191, -0.801, -2.574]} />
      <mesh name="cliff_01023" geometry={nodes.cliff_01023.geometry} material={materials['rock_dark.001']} position={[-40.161, -15.217, 145.967]} rotation={[-3.008, -0.128, 0.722]} />
      <mesh name="cliff_01016" geometry={nodes.cliff_01016.geometry} material={materials['rock_dark.001']} position={[70.669, -15.437, 77.37]} rotation={[-0.432, -1.25, -2.849]} />
      <mesh name="cliff_01024" geometry={nodes.cliff_01024.geometry} material={materials['rock_dark.001']} position={[-71.454, -15.603, 128.722]} rotation={[-3.001, 0.336, 0.658]} />
      <mesh name="cliff_01017" geometry={nodes.cliff_01017.geometry} material={materials['rock_dark.001']} position={[59.798, -14.838, 111.902]} rotation={[-0.597, 1.334, -1.853]} />
      <mesh name="cliff_01025" geometry={nodes.cliff_01025.geometry} material={materials['rock_dark.001']} position={[-92.908, -15.004, 99.561]} rotation={[-0.194, -0.819, -2.58]} />
      <mesh name="cliff_01018" geometry={nodes.cliff_01018.geometry} material={materials['rock_dark.001']} position={[33.917, -12.89, 136.813]} rotation={[-0.257, 1.024, -2.216]} />
      <mesh name="cliff_01026" geometry={nodes.cliff_01026.geometry} material={materials['rock_dark.001']} position={[-97.737, -13.056, 63.965]} rotation={[-0.324, -1.144, -2.734]} />
      <mesh name="cliff_01019" geometry={nodes.cliff_01019.geometry} material={materials['rock_dark.001']} position={[1.121, -12.89, 147.947]} rotation={[-0.138, 0.293, -2.397]} />
      <mesh name="cliff_02013" geometry={nodes.cliff_02013.geometry} material={materials['rock_dark.001']} position={[54.251, -22.368, 22.274]} rotation={[-0.837, 0.986, 0.82]} />
      <mesh name="cliff_02021" geometry={nodes.cliff_02021.geometry} material={materials['rock_dark.001']} position={[-17.29, -22.534, 147.994]} rotation={[-0.733, -0.912, -0.544]} />
      <mesh name="cliff_02014" geometry={nodes.cliff_02014.geometry} material={materials['rock_dark.001']} position={[63.381, -22.674, 41.783]} rotation={[-1.001, 1.063, 1.012]} />
      <mesh name="cliff_02022" geometry={nodes.cliff_02022.geometry} material={materials['rock_dark.001']} position={[-38.427, -20.392, 143.847]} rotation={[-0.64, -0.815, -0.422]} />
      <mesh name="cliff_02015" geometry={nodes.cliff_02015.geometry} material={materials['rock_dark.001']} position={[68.296, -20.612, 76.004]} rotation={[-0.578, 0.723, 0.481]} />
      <mesh name="cliff_02023" geometry={nodes.cliff_02023.geometry} material={materials['rock_dark.001']} position={[-68.95, -20.778, 127.612]} rotation={[-1.192, -1.114, -1.08]} />
      <mesh name="cliff_02016" geometry={nodes.cliff_02016.geometry} material={materials['rock_dark.001']} position={[61.249, -20.013, 114.225]} rotation={[-2.7, -0.292, -2.932]} />
      <mesh name="cliff_02024" geometry={nodes.cliff_02024.geometry} material={materials['rock_dark.001']} position={[-95.64, -20.179, 99.362]} rotation={[-0.973, 1.053, 0.98]} />
      <mesh name="cliff_02017" geometry={nodes.cliff_02017.geometry} material={materials['rock_dark.001']} position={[34.524, -18.065, 139.484]} rotation={[-2.72, 0.013, -3.073]} />
      <mesh name="cliff_02025" geometry={nodes.cliff_02025.geometry} material={materials['rock_dark.001']} position={[-100.252, -18.231, 62.878]} rotation={[-0.641, 0.817, 0.572]} />
      <mesh name="cliff_02018" geometry={nodes.cliff_02018.geometry} material={materials['rock_dark.001']} position={[-0.238, -18.065, 150.325]} rotation={[-2.589, 0.677, 2.847]} />
      <mesh name="cliff_group_01023" geometry={nodes.cliff_group_01023.geometry} material={materials['rock_dark.001']} position={[60.921, -20.829, 36.612]} rotation={[-2.692, 1.349, 2.849]} />
      <mesh name="cliff_group_01035" geometry={nodes.cliff_group_01035.geometry} material={materials['rock_dark.001']} position={[-32.801, -18.547, 144.914]} rotation={[-0.106, -0.429, 0.104]} />
      <mesh name="cliff_group_01024" geometry={nodes.cliff_group_01024.geometry} material={materials['rock_dark.001']} position={[71.794, -21.135, 55.172]} rotation={[-2.85, 1.231, 3.013]} />
      <mesh name="cliff_group_01036" geometry={nodes.cliff_group_01036.geometry} material={materials['rock_dark.001']} position={[-54.018, -20.209, 142.5]} rotation={[-0.101, -0.304, 0.117]} />
      <mesh name="cliff_group_01025" geometry={nodes.cliff_group_01025.geometry} material={materials['rock_dark.001']} position={[69.76, -19.073, 91.749]} rotation={[-0.597, 1.4, 0.738]} />
      <mesh name="cliff_group_01037" geometry={nodes.cliff_group_01037.geometry} material={materials['rock_dark.001']} position={[-82.523, -19.239, 119.499]} rotation={[-0.134, -0.769, 0.054]} />
      <mesh name="cliff_group_01026" geometry={nodes.cliff_group_01026.geometry} material={materials['rock_dark.001']} position={[68.435, -18.767, 70.279]} rotation={[-0.349, 1.287, 0.484]} />
      <mesh name="cliff_group_01038" geometry={nodes.cliff_group_01038.geometry} material={materials['rock_dark.001']} position={[-64.411, -18.933, 131.104]} rotation={[-0.153, -0.893, 0.028]} />
      <mesh name="cliff_group_01027" geometry={nodes.cliff_group_01027.geometry} material={materials['rock_dark.001']} position={[58.433, -18.168, 119.21]} rotation={[-3.002, -0.809, -2.893]} />
      <mesh name="cliff_group_01039" geometry={nodes.cliff_group_01039.geometry} material={materials['rock_dark.001']} position={[-98.002, -18.334, 94.145]} rotation={[-2.653, 1.365, 2.809]} />
      <mesh name="cliff_group_01028" geometry={nodes.cliff_group_01028.geometry} material={materials['rock_dark.001']} position={[67.366, -18.474, 99.642]} rotation={[-2.98, -0.933, -2.864]} />
      <mesh name="cliff_group_01040" geometry={nodes.cliff_group_01040.geometry} material={materials['rock_dark.001']} position={[-87.48, -18.64, 112.907]} rotation={[-2.834, 1.249, 2.996]} />
      <mesh name="cliff_group_01029" geometry={nodes.cliff_group_01029.geometry} material={materials['rock_dark.001']} position={[45.096, -16.526, 127.724]} rotation={[-3.025, -0.601, -2.928]} />
      <mesh name="cliff_group_01041" geometry={nodes.cliff_group_01041.geometry} material={materials['rock_dark.001']} position={[-97.001, -16.692, 78.354]} rotation={[-1.291, 1.471, 1.438]} />
      <mesh name="cliff_group_01030" geometry={nodes.cliff_group_01030.geometry} material={materials['rock_dark.001']} position={[30.225, -16.22, 143.266]} rotation={[-3.034, -0.476, -2.944]} />
      <mesh name="cliff_group_01031" geometry={nodes.cliff_group_01031.geometry} material={materials['rock_dark.001']} position={[-5.962, -16.22, 150.204]} rotation={[-3.042, 0.263, -3.02]} />
      <mesh name="cliff_group_01032" geometry={nodes.cliff_group_01032.geometry} material={materials['rock_dark.001']} position={[15.503, -16.526, 148.813]} rotation={[-3.045, 0.138, -3.007]} />
      <mesh name="cliff_group_01017" geometry={nodes.cliff_group_01017.geometry} material={materials['rock_dark.001']} position={[16.327, -15.481, 23.554]} rotation={[-2.641, -1.115, -2.579]} />
      <mesh name="cliff_group_01018" geometry={nodes.cliff_group_01018.geometry} material={materials['rock_dark.001']} position={[20.913, -16.432, 5.591]} rotation={[0.154, 1.428, 2.885]} />
      <mesh name="cliff_group_01019" geometry={nodes.cliff_group_01019.geometry} material={materials['rock_dark.001']} position={[20.305, -16.284, 8.299]} rotation={[-2.209, -1.305, -2.12]} />
      <mesh name="cliff_group_01020" geometry={nodes.cliff_group_01020.geometry} material={materials['rock_dark.001']} position={[21.428, -18.879, -8.033]} rotation={[0.154, 1.428, 2.885]} />
      <mesh name="cliff_group_01016" geometry={nodes.cliff_group_01016.geometry} material={materials['rock_dark.001']} position={[45.197, -12.525, 10.545]} rotation={[-1.584, -0.223, -1.76]} />
      <mesh name="cliff_group_01034" geometry={nodes.cliff_group_01034.geometry} material={materials['rock_dark.001']} position={[36.659, -11.535, 8.885]} rotation={[1.471, -0.446, 1.998]} />
      <mesh name="cliff_group_01042" geometry={nodes.cliff_group_01042.geometry} material={materials['rock_dark.001']} position={[29.315, -12.028, 2.749]} rotation={[1.288, -0.034, 1.779]} />
      <mesh name="cliff_group_01043" geometry={nodes.cliff_group_01043.geometry} material={materials['rock_dark.001']} position={[29.089, -6.812, 26.724]} rotation={[-1.715, 0.01, 1.802]} />
      <mesh name="cliff_group_01045" geometry={nodes.cliff_group_01045.geometry} material={materials['rock_dark.001']} position={[40.584, -14.718, 35.129]} rotation={[-2.749, -1.061, -2.377]} scale={[1, 1.253, 1.657]} />
      <mesh name="cliff_group_01046" geometry={nodes.cliff_group_01046.geometry} material={materials['rock_dark.001']} position={[33.527, -17.068, 41.54]} rotation={[-2.948, -0.254, -2.674]} />
      <mesh name="cliff_group_01047" geometry={nodes.cliff_group_01047.geometry} material={materials['rock_dark.001']} position={[35.49, -9.789, 35.757]} rotation={[-0.914, 0.527, 3.141]} />
      <mesh name="cliff_group_01048" geometry={nodes.cliff_group_01048.geometry} material={materials['rock_dark.001']} position={[40.277, -7.017, 30.779]} rotation={[-2.171, 0.153, 2.207]} />
      <mesh name="cliff_group_01049" geometry={nodes.cliff_group_01049.geometry} material={materials['rock_dark.001']} position={[21.225, -6.402, 25.21]} rotation={[-1.431, 0.036, -1.016]} />
      <mesh name="cliff_group_01051" geometry={nodes.cliff_group_01051.geometry} material={materials['rock_dark.001']} position={[20.435, -12.139, 45.401]} rotation={[-2.917, -0.681, 2.021]} scale={0.467} />
      <mesh name="cliff_group_01052" geometry={nodes.cliff_group_01052.geometry} material={materials['rock_dark.001']} position={[19.491, -18.095, 46.076]} rotation={[-3.02, -0.437, -2.837]} scale={0.467} />
      <mesh name="cliff_group_01053" geometry={nodes.cliff_group_01053.geometry} material={materials['rock_dark.001']} position={[16.563, -12.977, 46.315]} rotation={[-3.02, -0.437, -2.837]} scale={[0.467, 0.747, 0.467]} />
      <mesh name="cliff_group_01054" geometry={nodes.cliff_group_01054.geometry} material={materials['rock_dark.001']} position={[16.563, -12.977, 46.315]} rotation={[-3.02, -0.437, -2.837]} scale={0.467} />
      <mesh name="cliff_group_01055" geometry={nodes.cliff_group_01055.geometry} material={materials['rock_dark.001']} position={[11.849, -7.9, 37.251]} rotation={[1.61, -0.168, 2.544]} scale={0.467} />
      <mesh name="cliff_group_01056" geometry={nodes.cliff_group_01056.geometry} material={materials['rock_dark.001']} position={[16.899, -7.406, 33.124]} rotation={[1.61, -0.168, 2.544]} scale={0.467} />
      <mesh name="cliff_group_01057" geometry={nodes.cliff_group_01057.geometry} material={materials['rock_dark.001']} position={[19.532, -8.137, 38.766]} rotation={[1.61, -0.168, 2.544]} scale={[0.877, 0.927, 0.467]} />
      <mesh name="rock_small_01001" geometry={nodes.rock_small_01001.geometry} material={materials['rock_dark.001']} position={[40.164, -15.85, 25.737]} rotation={[-2.422, -0.969, 0.882]} />
      <mesh name="rock_small_01002" geometry={nodes.rock_small_01002.geometry} material={materials['rock_dark.001']} position={[46.601, -24.688, 3.71]} rotation={[2.213, 0.3, 0.439]} />
      <mesh name="rock_small_01003" geometry={nodes.rock_small_01003.geometry} material={materials['rock_dark.001']} position={[52.772, -15.269, 17.982]} rotation={[-0.391, -0.038, 3.013]} scale={[2.32, 1.18, 1.75]} />
      <mesh name="rock_small_01004" geometry={nodes.rock_small_01004.geometry} material={materials['rock_dark.001']} position={[47.741, -15.361, 4.481]} rotation={[2.929, 0.845, 1.789]} />
      <mesh name="rock_medium_02" geometry={nodes.rock_medium_02.geometry} material={materials['rock_dark.001']} position={[42.563, -20.077, 38.073]} rotation={[-2.39, -0.518, -1.351]} />
      <mesh name="rock_medium_02001" geometry={nodes.rock_medium_02001.geometry} material={materials['rock_dark.001']} position={[49.334, -24.121, 8.252]} rotation={[-2.383, -0.953, 1.385]} />
    </group>
  )
}

useGLTF.preload('./models/world/split/Cliffs.glb')
