/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/FallCollider.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody, CuboidCollider } from "@react-three/rapier";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./models/world/split/FallCollider.glb");
  return (
    <RigidBody name="fallCollider" type="fixed" friction={1} colliders="cuboid">
      <CuboidCollider position={[3, -29, 0]} args={[1, 0.5, 1]} />
      <group {...props} dispose={null}>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["Material.005"]}
          position={[45.623, -56.681, 33.374]}
          scale={[163.655, 1, 216.448]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("./models/world/split/FallCollider.glb");
