/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Floor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Floor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="ground_church" geometry={nodes.ground_church.geometry} material={materials['ground_snow.001']} position={[-125.494, -5.946, -68.13]} rotation={[0, 0.295, 0]} />
      <mesh name="ground_santa" geometry={nodes.ground_santa.geometry} material={materials['ground_snow.001']} position={[-67.485, -7.142, 0.611]} />
      <mesh name="ground_start" geometry={nodes.ground_start.geometry} material={materials['ground_snow.001']} position={[-17.896, -15.089, 0.57]} />
      <mesh name="ground_village" geometry={nodes.ground_village.geometry} material={materials['ground_snow.001']} position={[-134.773, -11.106, 48.316]} rotation={[0.006, 0.006, 0.027]} />
      <mesh name="ground_lower" geometry={nodes.ground_lower.geometry} material={materials['ground_snow.001']} position={[-16.7, -25.618, 75.124]} rotation={[Math.PI, -1.094, Math.PI]} scale={[2.393, 1, 2.689]} />
      <mesh name="ground_village_2" geometry={nodes.ground_village_2.geometry} material={materials['ground_snow.001']} position={[-123.211, -12.611, 27.317]} rotation={[Math.PI, -1.364, Math.PI]} />
      <group name="road_1" position={[-90.921, -9.376, 43.831]} rotation={[-0.058, -0.296, -0.196]}>
        <mesh name="Scene042" geometry={nodes.Scene042.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene042_1" geometry={nodes.Scene042_1.geometry} material={materials['road_asphalt.001']} />
      </group>
      <group name="road_4" position={[-39.878, -18.316, 54.488]} rotation={[3.113, 0.093, -2.962]}>
        <mesh name="Scene042" geometry={nodes.Scene042.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene042_1" geometry={nodes.Scene042_1.geometry} material={materials['road_asphalt.001']} />
      </group>
      <group name="road_2" position={[-74.424, -12.51, 46.156]} rotation={[-3.114, 0.216, -2.993]}>
        <mesh name="Scene008" geometry={nodes.Scene008.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene008_1" geometry={nodes.Scene008_1.geometry} material={materials['road_asphalt.001']} />
      </group>
      <group name="road_3" position={[-57.738, -15.517, 52.487]} rotation={[0.163, -0.27, -0.096]}>
        <mesh name="Scene009" geometry={nodes.Scene009.geometry} material={materials['ground_snow.001']} />
        <mesh name="Scene009_1" geometry={nodes.Scene009_1.geometry} material={materials['road_asphalt.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/world/split/Floor.glb')
