/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/IceFloor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/IceFloor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="IceFloor" geometry={nodes.IceFloor.geometry} material={materials.ice} position={[6.668, -19.655, 107.94]} rotation={[-3.114, -1.1, -3.113]} scale={[1, 0.32, 1]} />
    </group>
  )
}

useGLTF.preload('./models/world/split/IceFloor.glb')
