/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/LowerLevel.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/LowerLevel.glb')
  return (
    <group {...props} dispose={null}>
      {/* <mesh name="collectible_1" geometry={nodes.collectible_1.geometry} material={materials['Material.003']} position={[10.298, -15.771, 104.126]} /> */}
      <mesh name="1222_Iceberg" geometry={nodes['1222_Iceberg'].geometry} material={materials.ice} position={[38.586, -47.496, 136.851]} rotation={[Math.PI / 2, 0, 0]} scale={0.718} />
      <mesh name="1222_Iceberg001" geometry={nodes['1222_Iceberg001'].geometry} material={materials.ice} position={[-1.907, -21.454, 135.62]} rotation={[Math.PI / 2, 0, 0]} scale={0.061} />
      <mesh name="1222_Iceberg002" geometry={nodes['1222_Iceberg002'].geometry} material={materials.ice} position={[-8.327, -21.736, 133.032]} rotation={[Math.PI / 2, 0, -2.708]} scale={[0.177, 0.097, 0.129]} />
      <mesh name="1222_Iceberg003" geometry={nodes['1222_Iceberg003'].geometry} material={materials.ice} position={[-18.376, -21.414, 121.87]} rotation={[Math.PI / 2, 0, -2.708]} scale={[0.178, 0.098, 0.13]} />
      <mesh name="1222_Iceberg004" geometry={nodes['1222_Iceberg004'].geometry} material={materials.ice} position={[36.19, -23.776, 94.299]} rotation={[Math.PI / 2, 0, 0]} scale={0.125} />
      <mesh name="1222_Iceberg005" geometry={nodes['1222_Iceberg005'].geometry} material={materials.ice} position={[15.974, -23.498, 75.588]} rotation={[Math.PI / 2, 0, 1.541]} scale={[0.114, 0.204, 0.154]} />
      <group name="pine_medium_snowy_01002" position={[-79.394, -19.3, 70.189]} rotation={[2.328, -0.926, 2.272]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01009" position={[-85.514, -19.752, 77.934]} rotation={[2.317, -0.921, 2.252]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01010" position={[-74.726, -18.869, 93.144]} rotation={[3.029, -1.092, 2.895]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01011" position={[-78.58, -19.215, 86.074]} rotation={[2.328, -0.926, 2.272]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01012" position={[-68.345, -18.457, 78.209]} rotation={[3.029, -1.092, 2.895]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01013" position={[-64.643, -18.676, 96.141]} rotation={[2.474, -1.043, 2.501]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01014" position={[-74.258, -18.694, 101.451]} rotation={[2.64, -1.039, 2.75]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01015" position={[-62.465, -18.202, 71.578]} rotation={[2.858, -1.077, 2.676]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01016" position={[-63.891, -18.259, 105.754]} rotation={[-2.906, -1.083, -2.815]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01017" position={[-71.079, -18.457, 107.76]} rotation={[2.64, -1.039, 2.75]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01018" position={[-60.754, -18.307, 77.94]} rotation={[2.858, -1.077, 2.676]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01019" position={[-62.864, -18.59, 89.974]} rotation={[3.029, -1.092, 2.895]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01020" position={[-65.071, -19.385, 112.372]} rotation={[3.03, 0.799, -2.968]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01006" position={[-40.968, -20.439, 127.875]} rotation={[0.02, -0.201, -0.058]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01007" position={[-85.803, -19.782, 86.609]} rotation={[2.317, -0.921, 2.252]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01008" position={[-77.239, -19.131, 80.901]} rotation={[2.328, -0.926, 2.272]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01009" position={[-83.471, -18.984, 98.061]} rotation={[2.725, -1.057, 2.825]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01010" position={[-71.944, -18.748, 72.755]} rotation={[2.328, -0.926, 2.272]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01011" position={[-64.418, -19.26, 84.298]} rotation={[3.029, -1.092, 2.895]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01012" position={[-80.021, -19.348, 75.158]} rotation={[2.328, -0.926, 2.272]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01005" position={[-52.329, -20.75, 125.763]} rotation={[-0.102, -0.2, -0.013]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01004" position={[-70.678, -18.652, 85.697]} rotation={[3.029, -1.092, 2.895]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01005" position={[-70.318, -18.64, 65.719]} rotation={[2.323, -0.924, 2.28]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01006" position={[-86.748, -19.863, 66.817]} rotation={[2.328, -0.926, 2.272]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01007" position={[-88.637, -19.195, 92.937]} rotation={[2.725, -1.057, 2.825]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01008" position={[-79.442, -18.687, 107.581]} rotation={[2.64, -1.039, 2.75]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01009" position={[-90.573, -20.152, 70.808]} rotation={[2.317, -0.921, 2.252]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01010" position={[-91.438, -20.217, 82.267]} rotation={[2.317, -0.921, 2.252]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01011" position={[-73.134, -20.687, 115.216]} rotation={[0.188, -0.601, 0.317]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="Tent_Cube001" position={[-46.776, -18.403, 123.227]} rotation={[1.679, 0.1, -3.076]} scale={3.824}>
        <mesh name="Tent_Cube001_1" geometry={nodes.Tent_Cube001_1.geometry} material={materials.Tent_M} />
        <mesh name="Tent_Cube001_2" geometry={nodes.Tent_Cube001_2.geometry} material={materials.Tent_S} />
      </group>
      <mesh name="rock_small_01" geometry={nodes.rock_small_01.geometry} material={materials['rock_dark.001']} position={[-51.785, -19.739, 99.617]} rotation={[-0.017, -0.201, 0.005]} scale={[1.057, 1, 1.917]} />
      <mesh name="rock_small_02" geometry={nodes.rock_small_02.geometry} material={materials['rock_dark.001']} position={[-41.64, -19.8, 98.408]} rotation={[-0.106, 0.6, 0.11]} scale={[1.071, 0.63, 2.116]} />
      <group name="fence_snowy_03002" position={[-39.242, -20.078, 124.351]} rotation={[0.051, -0.2, -0.081]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="fence_snowy_03003" position={[-41.167, -20.188, 124.367]} rotation={[-0.035, -0.203, -0.492]}>
        <mesh name="Scene047" geometry={nodes.Scene047.geometry} material={materials.DarkWood} />
        <mesh name="Scene047_1" geometry={nodes.Scene047_1.geometry} material={materials['ground_snow.001']} />
      </group>
      <group name="log" position={[-41.725, -18.784, 110.267]} rotation={[1.498, -0.064, -0.825]} scale={[2.815, 2.208, 1.988]}>
        <mesh name="group1305922676" geometry={nodes.group1305922676.geometry} material={materials['pine_trunk.001']} />
        <mesh name="group1305922676_1" geometry={nodes.group1305922676_1.geometry} material={materials['light_wood_01.001']} />
      </group>
      <group name="log_2" position={[-53.237, -18.754, 107.199]} rotation={[1.62, 0.038, 0.942]} scale={[2.815, 2.208, 1.988]}>
        <mesh name="group1305922676001" geometry={nodes.group1305922676001.geometry} material={materials['pine_trunk.001']} />
        <mesh name="group1305922676001_1" geometry={nodes.group1305922676001_1.geometry} material={materials['light_wood_01.001']} />
      </group>
      <group name="firewoods_01" position={[-35.061, -20.362, 115.819]} rotation={[0.122, 1.104, -0.102]} scale={3.024}>
        <mesh name="Scene043" geometry={nodes.Scene043.geometry} material={materials['light_wood_01.001']} />
        <mesh name="Scene043_1" geometry={nodes.Scene043_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene043_2" geometry={nodes.Scene043_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <mesh name="Boat-ver1" geometry={nodes['Boat-ver1'].geometry} material={materials['Texture-base.014']} position={[-16.64, -18.236, 104.875]} rotation={[1.344, 0.032, 0.119]} scale={4.822} />
      <group name="Bonfire001" position={[-46.904, -18.304, 103.257]} scale={9.855}>
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.Wood} />
        <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials.WoodSide} />
        <mesh name="Cylinder004_2" geometry={nodes.Cylinder004_2.geometry} material={materials['rock_dark.001']} />
        <mesh name="Cylinder004_3" geometry={nodes.Cylinder004_3.geometry} material={materials.Wood} />
      </group>
      <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cube001_Cube004" geometry={nodes.Cube001_Cube004.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cube002_Cube005" geometry={nodes.Cube002_Cube005.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cube003_Cube006" geometry={nodes.Cube003_Cube006.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cube005_Cube008" geometry={nodes.Cube005_Cube008.geometry} material={materials['dark grey rough']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cube006_Cube001" geometry={nodes.Cube006_Cube001.geometry} material={materials['rough black']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <group name="Cube_Cube002" position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]}>
        <mesh name="Cube_Cube002_1" geometry={nodes.Cube_Cube002_1.geometry} material={materials['rough black']} />
        <mesh name="Cube_Cube002_2" geometry={nodes.Cube_Cube002_2.geometry} material={materials.Body} />
        <mesh name="Cube_Cube002_3" geometry={nodes.Cube_Cube002_3.geometry} material={materials.Yellow} />
        <mesh name="Cube_Cube002_4" geometry={nodes.Cube_Cube002_4.geometry} material={materials['car glass']} />
      </group>
      <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['rough black']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['rough black']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['rough black']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
      <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['rough black']} position={[-58.8, -21.419, 118.729]} rotation={[1.702, 0.076, -3.12]} />
    </group>
  )
}

useGLTF.preload('./models/world/split/LowerLevel.glb')
