/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/MerryChristmasCane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, CuboidCollider } from "@react-three/rapier";

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/MerryChristmasCane.glb')

  return (
    <group {...props} dispose={null}>
      <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text004" geometry={nodes.Text004.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text005" geometry={nodes.Text005.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text006" geometry={nodes.Text006.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text007" geometry={nodes.Text007.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text008" geometry={nodes.Text008.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text009" geometry={nodes.Text009.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text010" geometry={nodes.Text010.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text011" geometry={nodes.Text011.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text012" geometry={nodes.Text012.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text013" geometry={nodes.Text013.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
      <mesh name="Text014" geometry={nodes.Text014.geometry} material={materials.Material} position={[21.285, -6.056, 56.149]} rotation={[1.579, 0, 2.455]} />
    </group>

  )
}

useGLTF.preload('./models/world/split/MerryChristmasCane.glb')
