/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Start.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Start.glb')
  return (
    <group {...props} dispose={null}>
      <group name="pine_medium_snowy_01" position={[-9.514, -7.579, 13.128]} rotation={[0.05, 0, -0.091]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01001" position={[-25.172, -7.954, -9.69]} rotation={[-0.016, 0, 0.008]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01003" position={[-26.174, -8.441, 17.98]} rotation={[0.172, 0, -0.066]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01004" position={[-15.985, -8.057, -10.046]} rotation={[0.007, 0, -0.111]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01005" position={[-2.681, -8.664, -9.915]} rotation={[0.106, 0, 0.028]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01007" position={[-18.548, -7.986, 21.325]} rotation={[0.15, 0, -0.025]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_medium_snowy_01008" position={[-14.368, -7.376, 12.598]} rotation={[-0.106, 0, 0.076]}>
        <mesh name="Scene067" geometry={nodes.Scene067.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene067_1" geometry={nodes.Scene067_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene067_2" geometry={nodes.Scene067_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01" position={[-20.665, -7.801, 11.882]} rotation={[-0.1, 0, 0.007]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01001" position={[-21.326, -8.297, -14.875]} rotation={[-0.028, 0, 0.068]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01002" position={[-14.104, -8.101, 21.349]} rotation={[0.15, 0, -0.025]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01003" position={[-12.463, -8.127, -18.001]} rotation={[-0.038, 0, 0.004]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01004" position={[-6.771, -8.252, -14.805]} rotation={[-0.058, 0, 0.029]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_small_snowy_01006" position={[-9.722, -7.826, 18.271]} rotation={[0.179, 0, -0.077]}>
        <mesh name="Scene068" geometry={nodes.Scene068.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene068_1" geometry={nodes.Scene068_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene068_2" geometry={nodes.Scene068_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01" position={[-10.817, -7.655, -12.907]} rotation={[-0.088, 0, 0.05]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01001" position={[-3.55, -8.652, 20.158]} rotation={[0.179, 0, -0.077]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01002" position={[-21.38, -7.991, -11.827]} rotation={[-0.103, 0, 0.03]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
      <group name="pine_tall_snowy_01003" position={[-18.972, -7.307, 16.849]} rotation={[0.044, 0, -0.04]}>
        <mesh name="Scene065" geometry={nodes.Scene065.geometry} material={materials['pine_green.001']} />
        <mesh name="Scene065_1" geometry={nodes.Scene065_1.geometry} material={materials['pine_snow.001']} />
        <mesh name="Scene065_2" geometry={nodes.Scene065_2.geometry} material={materials['pine_trunk.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/world/split/Start.glb')
