/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k /Users/ajdemarco/Documents/Github/fetch-game/public/models/world/split/Village.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/world/split/Village.glb')
  return (
    <group {...props} dispose={null}>
      {/* <group name="Candy_Cane" position={[2.688, -0.018, 29.048]} rotation={[-Math.PI, 1.308, -Math.PI]} scale={[0.277, 1.856, 0.2]}>
        <mesh name="Object_0" geometry={nodes.Object_0.geometry} material={materials.candy_green} />
        <mesh name="Object_0_1" geometry={nodes.Object_0_1.geometry} material={materials.candy_white} />
        <mesh name="Object_0_2" geometry={nodes.Object_0_2.geometry} material={materials.candy_red} />
      </group> */}
      <group name="House_1" position={[64.067, -5.444, 128.518]} rotation={[Math.PI, -0.344, Math.PI]} scale={7}>
        <mesh name="Cube145" geometry={nodes.Cube145.geometry} material={materials.Plaster} />
        <mesh name="Cube145_1" geometry={nodes.Cube145_1.geometry} material={materials.Wood} />
        <mesh name="Cube145_2" geometry={nodes.Cube145_2.geometry} material={materials.Wood_Side} />
        <mesh name="Cube145_3" geometry={nodes.Cube145_3.geometry} material={materials.Windows} />
        <mesh name="Cube145_4" geometry={nodes.Cube145_4.geometry} material={materials.Wood_Light} />
        <mesh name="Cube145_5" geometry={nodes.Cube145_5.geometry} material={materials.Stone_Dark} />
        <mesh name="Cube145_6" geometry={nodes.Cube145_6.geometry} material={materials.Stone} />
        <mesh name="Cube145_7" geometry={nodes.Cube145_7.geometry} material={materials.RoofTiles_Red} />
        <mesh name="Cube145_8" geometry={nodes.Cube145_8.geometry} material={materials.Stone_Light} />
      </group>
      <group name="Blacksmith" position={[38.943, -7.416, 119.981]} rotation={[0, -0.211, -Math.PI]} scale={-7}>
        <mesh name="Cube000" geometry={nodes.Cube000.geometry} material={materials.Plaster} />
        <mesh name="Cube000_1" geometry={nodes.Cube000_1.geometry} material={materials.Wood_Light} />
        <mesh name="Cube000_2" geometry={nodes.Cube000_2.geometry} material={materials.Wood_Side} />
        <mesh name="Cube000_3" geometry={nodes.Cube000_3.geometry} material={materials.Stone_Light} />
        <mesh name="Cube000_4" geometry={nodes.Cube000_4.geometry} material={materials.Stone_Dark} />
        <mesh name="Cube000_5" geometry={nodes.Cube000_5.geometry} material={materials.Wood} />
        <mesh name="Cube000_6" geometry={nodes.Cube000_6.geometry} material={materials.Windows} />
        <mesh name="Cube000_7" geometry={nodes.Cube000_7.geometry} material={materials.RoofTiles_Red} />
      </group>
      <group name="Sawmill" position={[78.522, -5.5, 107.572]} rotation={[0, 1.472, Math.PI]} scale={-7}>
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials.RoofTiles_Red} />
        <mesh name="Cube047_1" geometry={nodes.Cube047_1.geometry} material={materials.Plaster} />
        <mesh name="Cube047_2" geometry={nodes.Cube047_2.geometry} material={materials.Wood_Side} />
        <mesh name="Cube047_3" geometry={nodes.Cube047_3.geometry} material={materials.DarkWood} />
        <mesh name="Cube047_4" geometry={nodes.Cube047_4.geometry} material={materials.Metal} />
        <mesh name="Cube047_5" geometry={nodes.Cube047_5.geometry} material={materials.Windows} />
        <mesh name="Cube047_6" geometry={nodes.Cube047_6.geometry} material={materials.Wood} />
        <mesh name="Cube047_7" geometry={nodes.Cube047_7.geometry} material={materials.Wood_Light} />
        <mesh name="Cube047_8" geometry={nodes.Cube047_8.geometry} material={materials.Stone_Dark} />
        <mesh name="Cube047_9" geometry={nodes.Cube047_9.geometry} material={materials.Stone_Dark} />
      </group>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Poste.001']} position={[-0.755, -8.506, 100.306]} rotation={[-1.572, 0.004, -2.913]} scale={3.873} />
      <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['Poste.001']} position={[-0.755, -8.506, 100.306]} rotation={[-1.572, 0.004, -2.913]} scale={3.873} />
      <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['Letreros.001']} position={[-0.755, -8.506, 100.306]} rotation={[-1.572, 0.004, -2.913]} scale={3.873} />
      <mesh name="group56958267" geometry={nodes.group56958267.geometry} material={materials.mat21} position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808} />
      <mesh name="group56958267001" geometry={nodes.group56958267001.geometry} material={materials.mat21} position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808} />
      <mesh name="group790830455" geometry={nodes.group790830455.geometry} material={materials.mat21} position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808} />
      <mesh name="group790830455001" geometry={nodes.group790830455001.geometry} material={materials.mat21} position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808} />
      <group name="group1038710627" position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808}>
        <mesh name="group1038710627_1" geometry={nodes.group1038710627_1.geometry} material={materials.mat21} />
        <mesh name="group1038710627_2" geometry={nodes.group1038710627_2.geometry} material={materials.mat23} />
        <mesh name="group1038710627_3" geometry={nodes.group1038710627_3.geometry} material={materials.mat12} />
      </group>
      <group name="group1038710627001" position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808}>
        <mesh name="group1038710627_1" geometry={nodes.group1038710627_1.geometry} material={materials.mat21} />
        <mesh name="group1038710627_2" geometry={nodes.group1038710627_2.geometry} material={materials.mat23} />
        <mesh name="group1038710627_3" geometry={nodes.group1038710627_3.geometry} material={materials.mat12} />
      </group>
      <mesh name="group1176710984" geometry={nodes.group1176710984.geometry} material={materials.mat21} position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808} />
      <mesh name="group1176710984001" geometry={nodes.group1176710984001.geometry} material={materials.mat21} position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808} />
      <group name="group1273453722" position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808}>
        <mesh name="group1273453722_1" geometry={nodes.group1273453722_1.geometry} material={materials.mat21} />
        <mesh name="group1273453722_2" geometry={nodes.group1273453722_2.geometry} material={materials.mat23} />
        <mesh name="group1273453722_3" geometry={nodes.group1273453722_3.geometry} material={materials.mat12} />
      </group>
      <group name="group1273453722001" position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808}>
        <mesh name="group1273453722_1" geometry={nodes.group1273453722_1.geometry} material={materials.mat21} />
        <mesh name="group1273453722_2" geometry={nodes.group1273453722_2.geometry} material={materials.mat23} />
        <mesh name="group1273453722_3" geometry={nodes.group1273453722_3.geometry} material={materials.mat12} />
      </group>
      <group name="group1899794681" position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808}>
        <mesh name="group1899794681_1" geometry={nodes.group1899794681_1.geometry} material={materials.mat21} />
        <mesh name="group1899794681_2" geometry={nodes.group1899794681_2.geometry} material={materials.mat23} />
        <mesh name="group1899794681_3" geometry={nodes.group1899794681_3.geometry} material={materials.mat12} />
      </group>
      <group name="group1899794681001" position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808}>
        <mesh name="group1899794681_1" geometry={nodes.group1899794681_1.geometry} material={materials.mat21} />
        <mesh name="group1899794681_2" geometry={nodes.group1899794681_2.geometry} material={materials.mat23} />
        <mesh name="group1899794681_3" geometry={nodes.group1899794681_3.geometry} material={materials.mat12} />
      </group>
      <group name="group1969675137" position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808}>
        <mesh name="group1969675137_1" geometry={nodes.group1969675137_1.geometry} material={materials.mat21} />
        <mesh name="group1969675137_2" geometry={nodes.group1969675137_2.geometry} material={materials['rough black']} />
        <mesh name="group1969675137_3" geometry={nodes.group1969675137_3.geometry} material={materials.mat12} />
      </group>
      <group name="group1969675137001" position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808}>
        <mesh name="group1969675137_1" geometry={nodes.group1969675137_1.geometry} material={materials.mat21} />
        <mesh name="group1969675137_2" geometry={nodes.group1969675137_2.geometry} material={materials['rough black']} />
        <mesh name="group1969675137_3" geometry={nodes.group1969675137_3.geometry} material={materials.mat12} />
      </group>
      <mesh name="group2019904400" geometry={nodes.group2019904400.geometry} material={materials['white rough']} position={[54.743, -6.069, 84.728]} rotation={[Math.PI / 2, 0, -2.451]} scale={2.808} />
      <mesh name="group2019904400001" geometry={nodes.group2019904400001.geometry} material={materials['white rough']} position={[63.533, -5.84, 86.948]} rotation={[1.8, -0.102, -2.744]} scale={2.808} />
    </group>
  )
}

useGLTF.preload('./models/world/split/Village.glb')
