/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/dog/doggo.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/dog/doggo_actions_all.glb')
  const { actions, names } = useAnimations(animations, group)

  /*
  39 - Idle
  40 - Idle Looking
  51 - Jump
  57 - Flying
  59 - Laying Wagging
  61 - Laying Sleep
  66 - Laying Active
  72 - Pick Up
  73 - Pick Up Idle
  75 - Put Down
  76 - Run Forward
  78 - Run Left
  80 - Run Right
  83 - Sitting
  84 - Sitting Looking
  94 - Flying
  105 - Trot
  107 - Trot Left
  109 - Trot Right
  119 - Walk Back
  122 - Walk Forward
  124 - Walk Left
  126 - Walk Right

  */

  const currentAnim = 40

  useEffect(() => {
    actions[names[currentAnim]].reset().fadeIn(0.5).play()
  }, [])

  console.log(names[currentAnim])

  return (
    <group scale={.005} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Arm_Labrador" scale={100}>
          <primitive object={nodes.Root_bone} />
          <skinnedMesh name="Labardor" geometry={nodes.Labardor.geometry} material={materials['Material.001']} skeleton={nodes.Labardor.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/dog/doggo_actions_all.glb')
