/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ajdemarco/Documents/Github/fetch-game/public/models/cabin/LogHut.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./models/cabin/LogHut.glb");
  return (
    <>
      <RigidBody colliders={"trimesh"} type="fixed">
        <group
          rotation-y={Math.PI}
          position={[10, 5, 20]}
          position-y={-0.4}
          scale={0.6}
          {...props}
          dispose={null}
        >
          <mesh
            geometry={nodes.Circle456.geometry}
            material={materials["LogHutV1.1Mat"]}
          />
          <mesh
            geometry={nodes.Circle456_1.geometry}
            material={materials["LogHutV1.1Mat"]}
          />
          <mesh
            geometry={nodes.Circle456_2.geometry}
            material={materials["LogHutV1.1Mat"]}
          />
          <mesh
            geometry={nodes.FloorV11.geometry}
            material={materials["LogHutV1.1Mat"]}
          />
          {/* <mesh geometry={nodes.LogDoorV11.geometry} material={materials.LogDoor1Mat} position={[-0.543, 2.281, 4.925]} scale={[0.213, 1.044, 0.208]} /> */}
          <mesh
            geometry={nodes.RoofV11.geometry}
            material={materials.LogHutStyle1RoofMat}
          />
          <group position={[5.681, 3.676, 0.231]} scale={[0.896, 0.931, 0.925]}>
            <mesh
              geometry={nodes.Cube614.geometry}
              material={materials["Wood.009"]}
            />
            <mesh
              geometry={nodes.Cube614_1.geometry}
              material={materials.GlassMat}
            />
          </group>
        </group>
      </RigidBody>
    </>
  );
}

useGLTF.preload("./models/cabin/LogHut.glb");
